.\" man page create by R# package system.
.TH IGRAPH.BUILDER 1 2000-01-01 "correlation.graph" "correlation.graph"
.SH NAME
correlation.graph \- create a network graph based on the item correlations
.SH SYNOPSIS
\fIcorrelation.graph(\fBx\fR as <generic> CorrelationMatrix, 
\fBthreshold\fR as double = 0.65, 
\fBpvalue\fR as double = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a network graph based on the item correlations
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a correlation matrix. 
.PP
.PP
\fBthreshold\fB \fR\- the absolute threshold value of the correlation value. 
.PP
.PP
\fBpvalue\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph.builder
.SH FILES
.PP
igraph.dll
.PP
