.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "dev.cur" "dev.cur"
.SH NAME
dev.cur \- returns a length-one named integer vector giving the number and name of the
.SH SYNOPSIS
\fIdev.cur();\fR
.SH DESCRIPTION
.PP
returns a length-one named integer vector giving the number and name of the 
 active device, or 1, the null device, if none is active.
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
