.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "plot" "plot"
.SH NAME
plot \- Generic X-Y Plotting
.SH SYNOPSIS
\fIplot(\fBgraphics\fR as any, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Generic X-Y Plotting
 
 Generic function for plotting of R objects.
.PP
.SH OPTIONS
.PP
\fBgraphics\fB \fR\- 
 the graphics context
. 
.PP
.PP
\fBargs\fB \fR\- plot arguments. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
