.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "rasterFont" "rasterFont"
.SH NAME
rasterFont \- 
.SH SYNOPSIS
\fIrasterFont(\fBname\fR as string, 
\fBsize\fR as double = 12, 
\fBstyle\fR as <integer> FontStyle = [Regular]);\fR
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
