.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "rasterPixels" "rasterPixels"
.SH NAME
rasterPixels \- convert the image to a collection of raster pixels
.SH SYNOPSIS
\fIrasterPixels(\fBimage\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
convert the image to a collection of raster pixels
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
A dataframe object that contains the raster pixel data
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
