.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "resizeImage" "resizeImage"
.SH NAME
resizeImage \- resize image to a new pixel size
.SH SYNOPSIS
\fIresizeImage(\fBimage\fR as any, 
\fBfactor\fR as double, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
resize image to a new pixel size
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -. 
.PP
.PP
\fBfactor\fB \fR\- 
 + a single number will be scale the image lager or smaller
 + a numeric vector with two element will specific the new size in pixel directly
 + other situation will throw a new exception
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
