.\" man page create by R# package system.
.TH GRAPHICS 1 2002-May "wmf" "wmf"
.SH NAME
wmf \- windows metafile device
.SH SYNOPSIS
\fIwmf(\fBimage\fR as any = \fB<NULL>\fR, 
\fBfile\fR as any = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
windows metafile device
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
