.\" man page create by R# package system.
.TH STRINGR 4 2000-Jan "fromXML" "fromXML"
.SH NAME
fromXML \- parse XML text data into R object
.SH SYNOPSIS
\fIfromXML(\fBstr\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse XML text data into R object
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- the xml text. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
base.dll
.PP
