.\" man page create by R# package system.
.TH STRINGR 4 2000-Jan "levenshtein" "levenshtein"
.SH NAME
levenshtein \- Compute the edit distance between two strings is defined as the
.SH SYNOPSIS
\fIlevenshtein(\fBx\fR as string, 
\fBy\fR as string);\fR
.SH DESCRIPTION
.PP
Compute the edit distance between two strings is defined as the 
 minimum number of edit operations required to transform one string 
 into another.
.PP
.SH OPTIONS
.PP
\fBx$\fB \fR\- -. 
.PP
.PP
\fBy$\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
base.dll
.PP
