.\" man page create by R# package system.
.TH STRINGR 4 2000-Jan "shortest_common_superstring" "shortest_common_superstring"
.SH NAME
shortest_common_superstring \- 
.SH SYNOPSIS
\fIshortest_common_superstring(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
stringr
.SH FILES
.PP
base.dll
.PP
