.\" man page create by R# package system.
.TH TABLEJOINT 1 2002-May "union_joint" "union_joint"
.SH NAME
union_joint \- 
.SH SYNOPSIS
\fIunion_joint(\fBx\fR as <generic> dataframe, 
\fBy\fR as <generic> dataframe, 
\fBnull\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
TableJoint
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
