.\" man page create by R# package system.
.TH GRAPHICS 1 2000-Jan "color.height_map" "color.height_map"
.SH NAME
color.height_map \- construct a color heigh map
.SH SYNOPSIS
\fIcolor.height_map(\fBcolors\fR as any, 
\fBlevels\fR as integer = 255, 
\fBdesc\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
construct a color heigh map
.PP
.SH OPTIONS
.PP
\fBcolors\fB \fR\- 
 the color set for construct the color height map, the colors used
 in this parameter is used as the checkpoint for evaluate the 
 intensity scale value. A raster image object also could be used
 in this parameter.
. 
.PP
.PP
\fBlevels\fB \fR\- -. 
.PP
.PP
\fBdesc\fB \fR\- 
 should this function reverse the color vector order?
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
graphics.dll
.PP
