.\" man page create by R# package system.
.TH GRAPHICS 1 2000-Jan "raster_convolution" "raster_convolution"
.SH NAME
raster_convolution \- 
.SH SYNOPSIS
\fIraster_convolution(\fBraster\fR as <generic> RasterScaler, 
\fBsize\fR as integer = 3, 
\fBstride\fR as integer = 1);\fR
.SH SEE ALSO
graphics
.SH FILES
.PP
graphics.dll
.PP
