.\" man page create by R# package system.
.TH GRAPHICS 1 2000-Jan "raster_vec" "raster_vec"
.SH NAME
raster_vec \- Convert a raster image object data as an intensity scale vector
.SH SYNOPSIS
\fIraster_vec(\fBraster\fR as <generic> RasterScaler);\fR
.SH DESCRIPTION
.PP
Convert a raster image object data as an intensity scale vector
.PP
.SH OPTIONS
.PP
\fBraster\fB \fR\- A specific raster image object. 
.PP
.SH SEE ALSO
graphics
.SH FILES
.PP
graphics.dll
.PP
