.\" man page create by R# package system.
.TH GRDEVICES3D 4 2000-Jan "camera" "camera"
.SH NAME
camera \- Create a new 3D camera object.
.SH SYNOPSIS
\fIcamera(\fBviewAngle\fR as any = \fB<NULL>\fR, 
\fBviewDistance\fR as double = -40, 
\fBfov\fR as double = 256, 
\fBsize\fR as any = "2560,1440", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a new 3D camera object.
.PP
.SH OPTIONS
.PP
\fBviewAngle\fB \fR\- -. 
.PP
.PP
\fBviewDistance\fB \fR\- -. 
.PP
.PP
\fBfov\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices3D
.SH FILES
.PP
graphics.dll
.PP
