.\" man page create by R# package system.
.TH GRDEVICES3D 4 2000-01-01 "line3D" "line3D"
.SH NAME
line3D \- 
.SH SYNOPSIS
\fIline3D(\fBa\fR as any, 
\fBb\fR as any, 
\fBpen\fR as any = "stroke: black; stroke-width: 5px; stroke-dash: solid;");\fR
.SH SEE ALSO
grDevices3D
.SH FILES
.PP
graphics.dll
.PP
