.\" man page create by R# package system.
.TH GRDEVICES3D 4 2000-01-01 "vector3D" "vector3D"
.SH NAME
vector3D \- Create a new 3D point
.SH SYNOPSIS
\fIvector3D(\fBx\fR as double, 
\fBy\fR as double, 
\fBz\fR as double = 0);\fR
.SH DESCRIPTION
.PP
Create a new 3D point
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBz\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices3D
.SH FILES
.PP
graphics.dll
.PP
