.\" man page create by R# package system.
.TH T-SNE 1 2000-Jan "t.SNE" "t.SNE"
.SH NAME
t.SNE \- create t-SNE algorithm module
.SH SYNOPSIS
\fIt.SNE(\fBperplexity\fR as double = 30, 
\fBdimension\fR as integer = 2, 
\fBepsilon\fR as double = 10);\fR
.SH DESCRIPTION
.PP
create t-SNE algorithm module
.PP
.SH OPTIONS
.PP
\fBperplexity\fB \fR\- -. 
.PP
.PP
\fBdimension\fB \fR\- -. 
.PP
.PP
\fBepsilon\fB \fR\- -. 
.PP
.SH SEE ALSO
t-SNE
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
