.\" man page create by R# package system.
.TH CNN 1 2000-Jan "ada_delta" "ada_delta"
.SH NAME
ada_delta \- Adaptive delta will look at the differences between the expected result and the current result to train the network.
.SH SYNOPSIS
\fIada_delta(\fBbatch_size\fR as integer, 
\fBl2_decay\fR as double = 0.001, 
\fBro\fR as double = 0.95);\fR
.SH DESCRIPTION
.PP
Adaptive delta will look at the differences between the expected result and the current result to train the network.
.PP
.SH OPTIONS
.PP
\fBbatch_size\fB \fR\- -. 
.PP
.PP
\fBl2_decay\fB \fR\- -. 
.PP
.PP
\fBro\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
