.\" man page create by R# package system.
.TH CNN 1 2000-Jan "ada_grad" "ada_grad"
.SH NAME
ada_grad \- The adaptive gradient trainer will over time sum up the square of
.SH SYNOPSIS
\fIada_grad(\fBbatch_size\fR as integer, 
\fBl2_decay\fR as double = 0.001);\fR
.SH DESCRIPTION
.PP
The adaptive gradient trainer will over time sum up the square of
 the gradient and use it to change the weights.
.PP
.SH OPTIONS
.PP
\fBbatch_size\fB \fR\- -. 
.PP
.PP
\fBl2_decay\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
