.\" man page create by R# package system.
.TH CNN 1 2000-Jan "adam" "adam"
.SH NAME
adam \- Adaptive Moment Estimation is an update to RMSProp optimizer. In this running average of both the
.SH SYNOPSIS
\fIadam(\fBbatch_size\fR as integer, 
\fBl2_decay\fR as double = 0.001, 
\fBbeta1\fR as double = 0.9, 
\fBbeta2\fR as double = 0.999);\fR
.SH DESCRIPTION
.PP
Adaptive Moment Estimation is an update to RMSProp optimizer. In this running average of both the
 gradients and their magnitudes are used.
.PP
.SH OPTIONS
.PP
\fBbatch_size\fB \fR\- -. 
.PP
.PP
\fBl2_decay\fB \fR\- -. 
.PP
.PP
\fBbeta1\fB \fR\- -. 
.PP
.PP
\fBbeta2\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
