.\" man page create by R# package system.
.TH CNN 1 2000-Jan "auto_encoder" "auto_encoder"
.SH NAME
auto_encoder \- 
.SH SYNOPSIS
\fIauto_encoder(\fBcnn\fR as any, 
\fBdataset\fR as <generic> SampleData[], 
\fBmax_loops\fR as integer = 100, 
\fBalgorithm\fR as <generic> TrainerAlgorithm = \fB<NULL>\fR, 
\fBaction\fR as <generic> RFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
