.\" man page create by R# package system.
.TH CNN 1 2000-Jan "CeNiN" "CeNiN"
.SH NAME
CeNiN \- load a CNN model from file
.SH SYNOPSIS
\fICeNiN(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
load a CNN model from file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
