.\" man page create by R# package system.
.TH CNN 1 2000-Jan "cnn" "cnn"
.SH NAME
cnn \- Create a new CNN model
.SH SYNOPSIS
\fIcnn(\fBfile\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a new CNN model
 
 Convolutional neural network (CNN) is a regularized type of feed-forward
 neural network that learns feature engineering by itself via filters 
 (or kernel) optimization. Vanishing gradients and exploding gradients, 
 seen during backpropagation in earlier neural networks, are prevented by 
 using regularized weights over fewer connections.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- 
 if the given model file parameter is not default nothing, then the new 
 CNN model object will be loaded from the specific given file, otherwise 
 a blank new model object will be created from the CNN layer model 
 builder.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
