.\" man page create by R# package system.
.TH CNN 1 2000-Jan "conv_layer" "conv_layer"
.SH NAME
conv_layer \- This layer uses different filters to find attributes of the data that
.SH SYNOPSIS
\fIconv_layer(\fBsx\fR as integer, 
\fBfilters\fR as integer, 
\fBstride\fR as integer = 1, 
\fBpadding\fR as integer = 0);\fR
.SH DESCRIPTION
.PP
This layer uses different filters to find attributes of the data that
 affects the result. As an example there could be a filter to find
 horizontal edges in an image.
.PP
.SH OPTIONS
.PP
\fBsx\fB \fR\- -. 
.PP
.PP
\fBfilters\fB \fR\- -. 
.PP
.PP
\fBstride\fB \fR\- -. 
.PP
.PP
\fBpadding\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
