.\" man page create by R# package system.
.TH CNN 1 2000-Jan "conv_transpose_layer" "conv_transpose_layer"
.SH NAME
conv_transpose_layer \- 
.SH SYNOPSIS
\fIconv_transpose_layer(\fBdims\fR as any, 
\fBfilter\fR as any, 
\fBfilters\fR as integer = 3, 
\fBstride\fR as integer = 1);\fR
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
