.\" man page create by R# package system.
.TH CNN 1 2000-Jan "detectObject" "detectObject"
.SH NAME
detectObject \- classify a object from a given image data
.SH SYNOPSIS
\fIdetectObject(\fBmodel\fR as <generic> CeNiN, 
\fBtarget\fR as <generic> Bitmap, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
classify a object from a given image data
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBtarget\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
