.\" man page create by R# package system.
.TH CNN 1 2000-Jan "dropout_layer" "dropout_layer"
.SH NAME
dropout_layer \- This layer will remove some random activations in order to
.SH SYNOPSIS
\fIdropout_layer(\fBdrop_prob\fR as double = 0.5);\fR
.SH DESCRIPTION
.PP
This layer will remove some random activations in order to
 defeat over-fitting.
.PP
.SH OPTIONS
.PP
\fBdrop_prob\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
