.\" man page create by R# package system.
.TH CNN 1 2000-Jan "full_connected_layer" "full_connected_layer"
.SH NAME
full_connected_layer \- Neurons in a fully connected layer have full connections to all
.SH SYNOPSIS
\fIfull_connected_layer(\fBsize\fR as integer);\fR
.SH DESCRIPTION
.PP
Neurons in a fully connected layer have full connections to all
 activations in the previous layer, as seen in regular Neural Networks.
 Their activations can hence be computed with a matrix multiplication
 followed by a bias offset.
.PP
.SH OPTIONS
.PP
\fBsize\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
