.\" man page create by R# package system.
.TH CNN 1 2000-Jan "maxout_layer" "maxout_layer"
.SH NAME
maxout_layer \- Implements Maxout nonlinearity that computes x to max(x)
.SH SYNOPSIS
\fImaxout_layer();\fR
.SH DESCRIPTION
.PP
Implements Maxout nonlinearity that computes x to max(x)
 where x is a vector of size group_size. Ideally of course,
 the input size should be exactly divisible by group_size
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
