.\" man page create by R# package system.
.TH CNN 1 2000-Jan "n_threads" "n_threads"
.SH NAME
n_threads \- get/set of the CNN parallel thread number
.SH SYNOPSIS
\fIn_threads(\fBn\fR as integer = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
get/set of the CNN parallel thread number
.PP
.SH OPTIONS
.PP
\fBn\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
