.\" man page create by R# package system.
.TH CNN 1 2000-Jan "nesterov" "nesterov"
.SH NAME
nesterov \- Another extension of gradient descent is due to Yurii Nesterov from 1983,[7] and has been subsequently generalized
.SH SYNOPSIS
\fInesterov(\fBbatch_size\fR as integer, 
\fBl2_decay\fR as double = 0.001);\fR
.SH DESCRIPTION
.PP
Another extension of gradient descent is due to Yurii Nesterov from 1983,[7] and has been subsequently generalized
.PP
.SH OPTIONS
.PP
\fBbatch_size\fB \fR\- -. 
.PP
.PP
\fBl2_decay\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
