.\" man page create by R# package system.
.TH CNN 1 2000-Jan "pool_layer" "pool_layer"
.SH NAME
pool_layer \- This layer will reduce the dataset by creating a smaller zoomed out
.SH SYNOPSIS
\fIpool_layer(\fBsx\fR as integer, 
\fBstride\fR as integer, 
\fBpadding\fR as integer);\fR
.SH DESCRIPTION
.PP
This layer will reduce the dataset by creating a smaller zoomed out
 version. In essence you take a cluster of pixels take the sum of them
 and put the result in the reduced position of the new image.
.PP
.SH OPTIONS
.PP
\fBsx\fB \fR\- -. 
.PP
.PP
\fBstride\fB \fR\- -. 
.PP
.PP
\fBpadding\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
