.\" man page create by R# package system.
.TH CNN 1 2000-Jan "predict" "predict"
.SH NAME
predict \- 
.SH SYNOPSIS
\fIpredict(\fBcnn\fR as any, 
\fBdataset\fR as any, 
\fBclass_labels\fR as any = "class_%d", 
\fBis_generative\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
