.\" man page create by R# package system.
.TH CNN 1 2000-Jan "relu_layer" "relu_layer"
.SH NAME
relu_layer \- This is a layer of neurons that applies the non-saturating activation
.SH SYNOPSIS
\fIrelu_layer();\fR
.SH DESCRIPTION
.PP
This is a layer of neurons that applies the non-saturating activation
 function f(x)=max(0,x). It increases the nonlinear properties of the
 decision function and of the overall network without affecting the
 receptive fields of the convolution layer.
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
