.\" man page create by R# package system.
.TH CNN 1 2000-Jan "saveModel" "saveModel"
.SH NAME
saveModel \- save the CNN model into a binary data file
.SH SYNOPSIS
\fIsaveModel(\fBmodel\fR as any, 
\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the CNN model into a binary data file
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
