.\" man page create by R# package system.
.TH CNN 1 2000-Jan "sigmoid_layer" "sigmoid_layer"
.SH NAME
sigmoid_layer \- Implements Sigmoid nonlinearity elementwise x to 1/(1+e^(-x))
.SH SYNOPSIS
\fIsigmoid_layer();\fR
.SH DESCRIPTION
.PP
Implements Sigmoid nonlinearity elementwise x to 1/(1+e^(-x))
 so the output is between 0 and 1.
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
