.\" man page create by R# package system.
.TH CNN 1 2000-Jan "softmax_layer" "softmax_layer"
.SH NAME
softmax_layer \- [*loss_layers] This layer will squash the result of the activations in the fully
.SH SYNOPSIS
\fIsoftmax_layer();\fR
.SH DESCRIPTION
.PP
[*loss_layers] This layer will squash the result of the activations in the fully
 connected layer and give you a value of 0 to 1 for all output activations.
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
