.\" man page create by R# package system.
.TH CNN 1 2000-Jan "tanh_layer" "tanh_layer"
.SH NAME
tanh_layer \- Implements Tanh nonlinearity elementwise x to tanh(x)
.SH SYNOPSIS
\fItanh_layer();\fR
.SH DESCRIPTION
.PP
Implements Tanh nonlinearity elementwise x to tanh(x)
 so the output is between -1 and 1.
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
