.\" man page create by R# package system.
.TH CNN 1 2000-Jan "training" "training"
.SH NAME
training \- Do CNN network model training
.SH SYNOPSIS
\fItraining(\fBcnn\fR as any, 
\fBdataset\fR as <generic> SampleData[], 
\fBmax_loops\fR as integer = 100, 
\fBverbose\fR as integer = 25, 
\fBalgorithm\fR as <generic> TrainerAlgorithm = \fB<NULL>\fR, 
\fBaction\fR as <generic> RFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do CNN network model training
.PP
.SH OPTIONS
.PP
\fBcnn\fB \fR\- -. 
.PP
.PP
\fBdataset\fB \fR\- -. 
.PP
.PP
\fBmax_loops\fB \fR\- -. 
.PP
.PP
\fBalgorithm\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CNN
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
