.\" man page create by R# package system.
.TH STRINGR 1 2002-May "concatenate" "concatenate"
.SH NAME
concatenate \- 
.SH SYNOPSIS
\fIconcatenate(\fBdata\fR as any, 
\fBcomma\fR as string = ",", 
\fBandalso\fR as string = "and", 
\fBetc\fR as string = "etc", 
\fBjoinSpace\fR as boolean = TRUE, 
\fBenUS\fR as boolean = FALSE);\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBcomma\fB \fR\- -. 
.PP
.PP
\fBandalso\fB \fR\- -. 
.PP
.PP
\fBetc\fB \fR\- -. 
.PP
.PP
\fBjoinSpace\fB \fR\- -. 
.PP
.PP
\fBenUS\fB \fR\- -. 
.PP
.SH VALUE
.PP
if the input data list contains no elements or it is 
 nothing, then this function will returns nothing
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
