.\" man page create by R# package system.
.TH STRINGR 1 2002-May "html" "html"
.SH NAME
html \- comvert any object to html text document
.SH SYNOPSIS
\fIhtml(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
comvert any object to html text document
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
