.\" man page create by R# package system.
.TH STRINGR 1 2002-May "paste" "paste"
.SH NAME
paste \- Concatenate Strings
.SH SYNOPSIS
\fIpaste(..., 
\fBsep\fR as string = " ", 
\fBcollapse\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Concatenate Strings
 
 string join with given delimiter, concatenate vectors after converting to character.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- one Or more R objects, to be converted to character vectors.. 
.PP
.PP
\fBsep\fB \fR\- 
 a character String To separate the terms. Not NA_character_.
. 
.PP
.PP
\fBcollapse\fB \fR\- 
 an optional character string to separate the results. Not NA_character_.
. 
.PP
.SH VALUE
.PP
A character vector of the concatenated values. This will be of length zero
 if all the objects are, unless collapse is non-NULL, in which case it is "" 
 (a single empty string).

        If any input into an element Of the result Is In UTF-8 (And none are declared
        With encoding "bytes", see Encoding), that element will be In UTF-8, otherwise 
        In the current encoding In which Case the encoding Of the element Is declared 
        If the current locale Is either Latin-1 Or UTF-8, at least one Of the corresponding
        inputs (including separators) had a declared encoding And all inputs were either 
        ASCII Or declared.

 If an input into an element Is declared With encoding "bytes", no translation will be done
 Of any Of the elements And the resulting element will have encoding "bytes". If collapse 
 Is non-NULL, this applies also To the second, collapsing, phase, but some translation may
 have been done In pasting Object together In the first phase.
.PP
.SH DETAILS
.PP
paste converts its arguments (via as.character) to character strings, 
 and concatenates them (separating them by the string given by sep). 
 If the arguments are vectors, they are concatenated term-by-term to 
 give a character vector result. Vector arguments are recycled as needed,
 with zero-length arguments being recycled to "" only if recycle0 is not 
 true or collapse is not NULL.

 Note that paste() coerces NA_character_, the character missing value, To 
 "NA" which may seem undesirable, e.g., When pasting two character vectors,
 Or very desirable, e.g. In paste("the value of p is ", p).

 paste0(..., collapse) Is equivalent to paste(..., sep = "", collapse), 
 slightly more efficiently.

 If a value Is specified For collapse, the values In the result are Then 
 concatenated into a Single String, With the elements being separated by
 the value Of collapse.
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
