.\" man page create by R# package system.
.TH STRINGR 1 2002-May "paste" "paste"
.SH NAME
paste \- string join with given delimiter
.SH SYNOPSIS
\fIpaste(\fBstrings\fR as string, 
\fBdeli\fR as string = " ");\fR
.SH DESCRIPTION
.PP
string join with given delimiter
.PP
.SH OPTIONS
.PP
\fBstrings$\fB \fR\- -. 
.PP
.PP
\fBdeli$\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
