.\" man page create by R# package system.
.TH STRINGR 1 2002-May "str_empty" "str_empty"
.SH NAME
str_empty \- test of the give character vector is empty string or not
.SH SYNOPSIS
\fIstr_empty(\fBstring\fR as string);\fR
.SH DESCRIPTION
.PP
test of the give character vector is empty string or not
.PP
.SH OPTIONS
.PP
\fB[string]\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
