.\" man page create by R# package system.
.TH STRINGR 1 2002-May "substr" "substr"
.SH NAME
substr \- Substrings of a Character Vector
.SH SYNOPSIS
\fIsubstr(\fBx\fR as any, 
\fBstart\fR as integer, 
\fBstop\fR as integer, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Substrings of a Character Vector
 
 Extract or replace substrings in a character vector.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a character vector.
. 
.PP
.PP
\fBstart\fB \fR\- integer. The first element To be replaced.. 
.PP
.PP
\fBstop\fB \fR\- integer. The last element to be replaced.. 
.PP
.SH VALUE
.PP
For \fBsubstr\fR, a character vector of the same length 
 and with the same attributes as x (after possible coercion).
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
