.\" man page create by R# package system.
.TH STRINGR 1 2002-May "text_equals" "text_equals"
.SH NAME
text_equals \- 
.SH SYNOPSIS
\fItext_equals(\fBx\fR as any, 
\fBy\fR as any, 
\fBnull_equals\fR as boolean = FALSE, 
\fBempty_equals\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
