.\" man page create by R# package system.
.TH STRINGR 1 2002-May "toString" "toString"
.SH NAME
toString \- Convert an R Object to a Character String
.SH SYNOPSIS
\fItoString(\fBx\fR as any, 
\fBformat\fR as string = \fB<NULL>\fR, 
\fBculture\fR as <generic> CultureInfo = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert an R Object to a Character String
 
 This is a helper function for format to produce a 
 single character string describing an R object.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- The object to be converted.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function just invoke the @\fBM:System.Object.ToString\fR method.
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
