.\" man page create by R# package system.
.TH STRINGR 1 2002-May "xml" "xml"
.SH NAME
xml \- Convert most of the R# object or VB.NET object to xml document string.
.SH SYNOPSIS
\fIxml(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Convert most of the R# object or VB.NET object to xml document string.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
stringr
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
