.\" man page create by R# package system.
.TH XLSX 4 2000-Jan "read.xlsx" "read.xlsx"
.SH NAME
read.xlsx \- read a sheet table in xlsx file as a \fBdataframe\fR object.
.SH SYNOPSIS
\fIread.xlsx(\fBfile\fR as any, 
\fBsheetIndex\fR as any = "Sheet1", 
\fBrow_names\fR as any = \fB<NULL>\fR, 
\fBraw\fR as boolean = FALSE, 
\fBcheck_names\fR as boolean = TRUE, 
\fBcheck_modes\fR as boolean = TRUE, 
\fBcomment_char\fR as string = #, 
\fBskip_rows\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
read a sheet table in xlsx file as a \fBdataframe\fR object.
.PP
.SH OPTIONS
.PP
\fBsheetIndex\fB \fR\- 
 the data sheet index or name for read data. the index value of 
 parameter should be start from base 1 if the type is an integer 
 index
. 
.PP
.PP
\fBcheck_modes\fB \fR\- 
 check the data type of each column in the dataframe? 
 this options is working if the \fBraw\fR parameter is 
 set to \fBFALSE\fR. 
. 
.PP
.PP
\fBcheck_names\fB \fR\- 
 make valid R# symbol names of each column in the dataframe?
 this options is working if the \fBraw\fR parameter is set
 to \fBFALSE\fR.
. 
.PP
.PP
\fBrow_names\fB \fR\- 
 A character vector for set row names of the generated dataframe, or 
 a character name in the dataframe, or an integer value to indicate
 that which column should be used as the row names of the 
 dataframe object.
 
 this options is working if the \fBraw\fR parameter is set
 to \fBFALSE\fR.
. 
.PP
.PP
\fBfile\fB \fR\- the file path of the target xlsx data file.. 
.PP
.SH SEE ALSO
xlsx
.SH FILES
.PP
base.dll
.PP
