.\" man page create by R# package system.
.TH XLSX 4 2000-01-01 "write.xlsx" "write.xlsx"
.SH NAME
write.xlsx \- 
.SH SYNOPSIS
\fIwrite.xlsx(\fBx\fR as any, 
\fBfile\fR as string, 
\fBsheetName\fR as string = "Sheet1", 
\fBrow_names\fR as boolean = TRUE, 
\fBfileEncoding\fR as any = "", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
xlsx
.SH FILES
.PP
base.dll
.PP
