.\" man page create by R# package system.
.TH IO 1 2000-Jan "flush" "flush"
.SH NAME
flush \- Commit all currently buffered writes to the given stream.
.SH SYNOPSIS
\fIflush(\fBresource\fR as any);\fR
.SH DESCRIPTION
.PP
Commit all currently buffered writes to the given stream.
.PP
.SH OPTIONS
.PP
\fBresource\fB \fR\- -. 
.PP
.SH SEE ALSO
io
.SH FILES
.PP
njl.dll
.PP
