.\" man page create by R# package system.
.TH IO 1 2000-Jan "open" "open"
.SH NAME
open \- Apply the function f to the result of open(args...; kwargs...)
.SH SYNOPSIS
\fIopen(\fBf\fR as any, 
\fBfilename\fR as string = \fB<NULL>\fR, 
\fBmode\fR as string = "r", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Apply the function f to the result of open(args...; kwargs...) 
 and close the resulting file descriptor upon completion.
.PP
.SH OPTIONS
.PP
\fBf\fB \fR\- -. 
.PP
.PP
\fBfilename\fB \fR\- -. 
.PP
.PP
\fBmode\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
io
.SH FILES
.PP
njl.dll
.PP
