.\" man page create by R# package system.
.TH IO 1 2000-Jan "read" "read"
.SH NAME
read \- open for reading
.SH SYNOPSIS
\fIread(\fBfile\fR as <generic> StreamReader, 
\fBtype\fR as string = "String");\fR
.SH DESCRIPTION
.PP
open for reading
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBtype\fB \fR\- -. 
.PP
.SH SEE ALSO
io
.SH FILES
.PP
njl.dll
.PP
