.\" man page create by R# package system.
.TH IO 1 2000-Jan "write" "write"
.SH NAME
write \- open for writing
.SH SYNOPSIS
\fIwrite(\fBfile\fR as <generic> StreamWriter, 
\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open for writing
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
io
.SH FILES
.PP
njl.dll
.PP
