.TH TEST_IFELSE 1 2025-Dec "" "test_ifelse"
.SH NAME
test_ifelse \- test_ifelse(x)
.SH SYNOPSIS
\fItest_ifelse(x)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.test_ifelse at ifelse.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
