.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "attributes" "attributes"
.SH NAME
attributes \- get or set element attribute values
.SH SYNOPSIS
\fIattributes(\fBelements\fR as any, 
\fBname\fR as string, 
\fBvalues\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get or set element attribute values
.PP
.SH OPTIONS
.PP
\fBelements\fB \fR\- -. 
.PP
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBvalues\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
dash style of the edge element could be:
 solid, dash, dot, dashdot, dashdotdot
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
