.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "compute.network" "compute.network"
.SH NAME
compute.network \- compute network properties' data
.SH SYNOPSIS
\fIcompute.network(\fBg\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
compute network properties' data
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
