.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "components" "components"
.SH NAME
components \- get subnetwork components directly by test node disconnections
.SH SYNOPSIS
\fIcomponents(\fBgraph\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
get subnetwork components directly by test node disconnections
.PP
.SH OPTIONS
.PP
\fBgraph\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
