.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "delete" "delete"
.SH NAME
delete \- 
.SH SYNOPSIS
\fIdelete(\fBg\fR as <generic> NetworkGraph, 
\fBnode\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
