.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "edges" "edges"
.SH NAME
edges \- get all edges in the given graph model
.SH SYNOPSIS
\fIedges(\fBg\fR as <generic> NetworkGraph);\fR
.SH DESCRIPTION
.PP
get all edges in the given graph model
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
