.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "extract.sub_graph" "extract.sub_graph"
.SH NAME
extract.sub_graph \- extract sub graph component by a specific
.SH SYNOPSIS
\fIextract.sub_graph(\fBg\fR as <generic> NetworkGraph, 
\fBnode_group\fR as string, 
\fBminVertices\fR as integer = 3);\fR
.SH DESCRIPTION
.PP
extract sub graph component by a specific 
 given node group tag data.
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBnode_group\fB \fR\- -. 
.PP
.PP
\fBminVertices\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
