.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "group" "group"
.SH NAME
group \- Make node groups by given type name
.SH SYNOPSIS
\fIgroup(\fBg\fR as <generic> NetworkGraph, 
\fBnodes\fR as string, 
\fBtype\fR as string);\fR
.SH DESCRIPTION
.PP
Make node groups by given type name
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBtype\fB \fR\- -. 
.PP
.PP
\fBnodes\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
