.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "has.edge" "has.edge"
.SH NAME
has.edge \- 
.SH SYNOPSIS
\fIhas.edge(\fBg\fR as <generic> NetworkGraph, 
\fBu\fR as string, 
\fBv\fR as string, 
\fBdirected\fR as boolean = FALSE);\fR
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
