.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "mass" "mass"
.SH NAME
mass \- set or get mass value of the nodes in the given graph
.SH SYNOPSIS
\fImass(\fBg\fR as <generic> NetworkGraph, 
\fBlabelID\fR as string = \fB<NULL>\fR, 
\fBmass\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set or get mass value of the nodes in the given graph
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBmass\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
