.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "metadata" "metadata"
.SH NAME
metadata \- create meta data for network tabular model.
.SH SYNOPSIS
\fImetadata(\fBtitle\fR as string, 
\fBdescription\fR as string = "n/a", 
\fBcreators\fR as string = \fB<NULL>\fR, 
\fBcreate_time\fR as string = \fB<NULL>\fR, 
\fBlinks\fR as string = \fB<NULL>\fR, 
\fBkeywords\fR as string = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create meta data for network tabular model.
.PP
.SH OPTIONS
.PP
\fBtitle\fB \fR\- -. 
.PP
.PP
\fBdescription\fB \fR\- -. 
.PP
.PP
\fBcreators\fB \fR\- -. 
.PP
.PP
\fBcreate_time\fB \fR\- -. 
.PP
.PP
\fBlinks\fB \fR\- -. 
.PP
.PP
\fBkeywords\fB \fR\- -. 
.PP
.PP
\fBmeta\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
