.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "node.names" "node.names"
.SH NAME
node.names \- set node data names
.SH SYNOPSIS
\fInode.names(\fBgraph\fR as <generic> NetworkGraph, 
\fBsetNames\fR as list = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set node data names
.PP
.SH OPTIONS
.PP
\fBgraph\fB \fR\- -. 
.PP
.PP
\fBsetNames\fB \fR\- 
 a list object with node id to node name mapping. if the given name label in this 
 list object is null or empty, then it will removes the name label value of the 
 specific node object.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
