.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "save.network" "save.network"
.SH NAME
save.network \- save the network graph
.SH SYNOPSIS
\fIsave.network(\fBg\fR as any, 
\fBfile\fR as string, 
\fBproperties\fR as any = ["*"], 
\fBmeta\fR as <generic> MetaData = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the network graph
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- the network graph object or [nodes, edges] table data.. 
.PP
.PP
\fBfile\fB \fR\- a folder file path for save the network data.. 
.PP
.PP
\fBproperties\fB \fR\- a list of property name for save in node table and edge table.. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
