.\" man page create by R# package system.
.TH IGRAPH 2 2000-01-01 "weight" "weight"
.SH NAME
weight \- set edge weight and get edge weights
.SH SYNOPSIS
\fIweight(\fBg\fR as any, 
\fBu\fR as string = \fB<NULL>\fR, 
\fBv\fR as string = \fB<NULL>\fR, 
\fBsetWeight\fR as double = 0, 
\fBdirected\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set edge weight and get edge weights
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBu\fB \fR\- -. 
.PP
.PP
\fBv\fB \fR\- -. 
.PP
.PP
\fBsetWeight\fB \fR\- -. 
.PP
.PP
\fBdirected\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
