.\" man page create by R# package system.
.TH IGRAPH 2 2000-Jan "xref" "xref"
.SH NAME
xref \- get node reference id list
.SH SYNOPSIS
\fIxref(\fBv\fR as <generic> V);\fR
.SH DESCRIPTION
.PP
get node reference id list
.PP
.SH OPTIONS
.PP
\fBv\fB \fR\- -. 
.PP
.SH SEE ALSO
igraph
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
