.\" man page create by R# package system.
.TH PACKAGE_UTILS 1 2020-12-26 "loadPackage" "loadPackage"
.SH NAME
loadPackage \- for debug used only
.SH SYNOPSIS
\fIloadPackage(\fBdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
for debug used only
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- -
.PP
.PP
\fBenv\fB \fR\- -
.PP
.SH SEE ALSO
package_utils
.SH FILES
.PP
devkit.dll
.PP
.SH COPYRIGHT
Copyright © I@xieguigang.me 2019
