.\" man page create by R# package system.
.TH IO 4 2000-Jan "dumpDf" "dumpDf"
.SH NAME
dumpDf \- Dumping a large json/xml dataset into a data table file
.SH SYNOPSIS
\fIdumpDf(\fBsource\fR as any, 
\fBprojection\fR as string, 
\fBtype\fR as <integer> sourceTypes = [JSON], 
\fBtrim\fR as string = \fB<NULL>\fR, 
\fBfilter\fR as <generic> RFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Dumping a large json/xml dataset into a data table file
.PP
.SH OPTIONS
.PP
\fBsource\fB \fR\- the source data object. 
.PP
.PP
\fBtype\fB \fR\- 
 the data format of the string content in source data object.
. 
.PP
.PP
\fBprojection\fB \fR\- 
 data fields in the content object from the source will be dump 
 to the data table object.. 
.PP
.PP
\fBtrim\fB \fR\- 
 some fields needs removes the additional blank space and new 
 line symbol. the field names in this parameter should be contains 
 in projection field list.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
IO
.SH FILES
.PP
base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
