.\" man page create by R# package system.
.TH RESHAPE2 1 2002-May "decompose" "decompose"
.SH NAME
decompose \- split dataframe by a cell string value split result
.SH SYNOPSIS
\fIdecompose(\fBdf\fR as <generic> dataframe, 
\fBby\fR as string, 
\fBsplit\fR as string = "[;,]\s*", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
split dataframe by a cell string value split result
.PP
.SH OPTIONS
.PP
\fBdf\fB \fR\- -. 
.PP
.PP
\fBby\fB \fR\- the colname for do the cell content split. 
.PP
.PP
\fBsplit\fB \fR\- the delimiter string expression for split the cell contents. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
reshape2
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
