.\" man page create by R# package system.
.TH RESHAPE2 1 2002-May "flip_list" "flip_list"
.SH NAME
flip_list \- flip the list key-value pair mapping to value-key pair mapping
.SH SYNOPSIS
\fIflip_list(\fBl\fR as list, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
flip the list key-value pair mapping to value-key pair mapping
.PP
.SH OPTIONS
.PP
\fBl\fB \fR\- Should be a tuple list object. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function only works for the value is character vector, 
 null value inside the list will be ignored
.PP
.SH SEE ALSO
reshape2
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
