.\" man page create by R# package system.
.TH RESHAPE2 1 2002-May "melt.list" "melt.list"
.SH NAME
melt.list \- 
.SH SYNOPSIS
\fImelt.list(\fBdata\fR as list, 
\fBna_rm\fR as boolean = FALSE, 
\fBvalue_name\fR as string = "value", 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
reshape2
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
