.\" man page create by R# package system.
.TH RESHAPE2 1 2002-May "melt.data.frame" "melt.data.frame"
.SH NAME
melt.data.frame \- 
.SH SYNOPSIS
\fImelt.data.frame(\fBdata\fR as <generic> dataframe, 
\fBna_rm\fR as boolean = FALSE, 
\fBvalue_name\fR as string = "value", 
..., 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
reshape2
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
