.\" man page create by R# package system.
.TH RESHAPE2 1 2002-May "zip_tuple" "zip_tuple"
.SH NAME
zip_tuple \- Aggregate two or more sequence
.SH SYNOPSIS
\fIzip_tuple(\fBzip\fR as any = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Aggregate two or more sequence
.PP
.SH OPTIONS
.PP
\fBzip\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
reshape2
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
