.\" man page create by R# package system.
.TH COLORBREWER 1 2000-Jan "TrIQ" "TrIQ"
.SH NAME
TrIQ \- get cutoff threshold value via TrIQ algorithm
.SH SYNOPSIS
\fITrIQ(\fBdata\fR as any, 
\fBq\fR as double = 0.65, 
\fBlevels\fR as integer = 30);\fR
.SH DESCRIPTION
.PP
get cutoff threshold value via TrIQ algorithm
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBq\fB \fR\- -. 
.PP
.PP
\fBlevels\fB \fR\- -. 
.PP
.SH VALUE
.PP
the threshold raw data value
.PP
.SH SEE ALSO
ColorBrewer
.SH FILES
.PP
graphics.dll
.PP
