.\" man page create by R# package system.
.TH NLP 1 2000-Jan "count" "count"
.SH NAME
count \- count tokens distribution
.SH SYNOPSIS
\fIcount(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
count tokens distribution
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
NLP
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
