.\" man page create by R# package system.
.TH NLP 1 2000-Jan "ldaCorpus" "ldaCorpus"
.SH NAME
ldaCorpus \- create a corpus for LDA modelling
.SH SYNOPSIS
\fIldaCorpus(\fBtext\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a corpus for LDA modelling
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- a vector of the character string data or a collection 
 of the text @\fBT:Microsoft.VisualBasic.Data.NLP.Model.Paragraph\fR data.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
NLP
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
