.\" man page create by R# package system.
.TH NLP 1 2000-Jan "segmentation" "segmentation"
.SH NAME
segmentation \- split the given text into multiple parts
.SH SYNOPSIS
\fIsegmentation(\fBtext\fR as any, 
\fBdelimiter\fR as string = ".?!", 
\fBchemical_name_rule\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
split the given text into multiple parts
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- -. 
.PP
.SH SEE ALSO
NLP
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
