.\" man page create by R# package system.
.TH NLP 1 2000-Jan "split_to_sentences" "split_to_sentences"
.SH NAME
split_to_sentences \- 
.SH SYNOPSIS
\fIsplit_to_sentences(\fBtext\fR as any, 
\fBdelimiter\fR as string = ".?!", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
NLP
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
