.\" man page create by R# package system.
.TH NLP 1 2000-Jan "word2vec" "word2vec"
.SH NAME
word2vec \- word2vec embedding
.SH SYNOPSIS
\fIword2vec(\fBtext\fR as any, 
\fBmethod\fR as <integer> TrainMethod = [Skip_Gram], 
\fBfreq\fR as integer = 3, 
\fBwin_size\fR as integer = 5, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
word2vec embedding
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- a vector of the character string data or a collection 
 of the text @\fBT:Microsoft.VisualBasic.Data.NLP.Model.Paragraph\fR data.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
NLP
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
