.\" man page create by R# package system.
.TH MATRIX 1 2000-01-02 "Matrix" "Matrix"
.SH NAME
Matrix \- 
.SH SYNOPSIS
\fIMatrix(\fBdata\fR as any = \fB<NULL>\fR, 
\fBnrow\fR as integer = 1, 
\fBncol\fR as integer = 1, 
\fBbyrow\fR as boolean = FALSE, 
\fBdimnames\fR as string = \fB<NULL>\fR, 
\fBsparse\fR as boolean = FALSE);\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBnrow\fB \fR\- -. 
.PP
.PP
\fBncol\fB \fR\- -. 
.PP
.PP
\fBbyrow\fB \fR\- -. 
.PP
.PP
\fBdimnames\fB \fR\- -. 
.PP
.PP
\fBsparse\fB \fR\- -. 
.PP
.SH SEE ALSO
Matrix
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
