.\" man page create by R# package system.
.TH REFLECTIONS 1 2002-May "class" "class"
.SH NAME
class \- Object Classes
.SH SYNOPSIS
\fIclass(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Object Classes
 
 R possesses a simple generic function mechanism which 
 can be used for an object-oriented style of programming. 
 Method dispatch takes place based on the class of the 
 first argument to the generic function.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a R object. 
.PP
.SH SEE ALSO
reflections
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
