.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-01-01 "asciiArt" "asciiArt"
.SH NAME
asciiArt \- convert bitmap to ascii characters
.SH SYNOPSIS
\fIasciiArt(\fBimage\fR as any, 
\fBcharSet\fR as string = "+-*.", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
convert bitmap to ascii characters
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
