.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "colorMap.legend" "colorMap.legend"
.SH NAME
colorMap.legend \- 
.SH SYNOPSIS
\fIcolorMap.legend(\fBcolors\fR as any, 
\fBticks\fR as double, 
\fBtitle\fR as string = "Color Map", 
\fBmapLevels\fR as integer = 60, 
\fBformat\fR as string = "G3", 
\fBtickAxisStroke\fR as any = "stroke: black; stroke-width: 5px; stroke-dash: solid;", 
\fBtickFont\fR as any = "font-style: normal; font-size: 12; font-family: Bookman Old Style;", 
\fBtitleFont\fR as any = "font-style: normal; font-size: 16; font-family: Bookman Old Style;", 
\fBunmapColor\fR as any = \fB<NULL>\fR, 
\fBforeColor\fR as any = "black", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
