.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "colorMap.legend" "colorMap.legend"
.SH NAME
colorMap.legend \- create a new color map legend
.SH SYNOPSIS
\fIcolorMap.legend(\fBcolors\fR as any, 
\fBticks\fR as any = "0,1", 
\fBtitle\fR as string = "Color Map", 
\fBmapLevels\fR as integer = 60, 
\fBformat\fR as string = "G3", 
\fBtickAxisStroke\fR as any = "stroke: black; stroke-width: 5px; stroke-dash: solid;", 
\fBtickFont\fR as any = "font-style: normal; font-size: 12; font-family: Bookman Old Style;", 
\fBtitleFont\fR as any = "font-style: normal; font-size: 16; font-family: Bookman Old Style;", 
\fBunmapColor\fR as any = \fB<NULL>\fR, 
\fBforeColor\fR as any = "black", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a new color map legend
.PP
.SH OPTIONS
.PP
\fBcolors\fB \fR\- -. 
.PP
.PP
\fBticks\fB \fR\- -. 
.PP
.PP
\fBtitle\fB \fR\- -. 
.PP
.PP
\fBmapLevels\fB \fR\- -. 
.PP
.PP
\fBformat\fB \fR\- -. 
.PP
.PP
\fBtickAxisStroke\fB \fR\- -. 
.PP
.PP
\fBtickFont\fB \fR\- -. 
.PP
.PP
\fBtitleFont\fB \fR\- -. 
.PP
.PP
\fBunmapColor\fB \fR\- -. 
.PP
.PP
\fBforeColor\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
