.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "contour_tracing" "contour_tracing"
.SH NAME
contour_tracing \- Measure object outline via run contour tracing algorithm.
.SH SYNOPSIS
\fIcontour_tracing(\fBx\fR as any, 
\fBy\fR as any, 
\fBfillDots\fR as integer = 1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Measure object outline via run contour tracing algorithm.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBfillDots\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
