.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-01-01 "draw.triangle" "draw.triangle"
.SH NAME
draw.triangle \- 
.SH SYNOPSIS
\fIdraw.triangle(\fBg\fR as <generic> IGraphics, 
\fBtopleft\fR as <generic> PointF, 
\fBsize\fR as <generic> SizeF, 
\fBcolor\fR as any = "black", 
\fBborder\fR as any = "stroke: black; stroke-width: 5px; stroke-dash: solid;");\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
