.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-01-01 "draw.legend" "draw.legend"
.SH NAME
draw.legend \- 
.SH SYNOPSIS
\fIdraw.legend(\fBcanvas\fR as any, 
\fBlegends\fR as <generic> LegendObject[], 
\fBlocation\fR as <generic> PointF, 
\fBborder\fR as any = "stroke: black; stroke-width: 5px; stroke-dash: solid;", 
\fBgSize\fR as any = "120,45", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
