.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "draw.rectangle" "draw.rectangle"
.SH NAME
draw.rectangle \- 
.SH SYNOPSIS
\fIdraw.rectangle(\fBcolor\fR as any, 
\fBrect\fR as any, 
\fBg\fR as <generic> IGraphics = \fB<NULL>\fR);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
