.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "draw.circle" "draw.circle"
.SH NAME
draw.circle \- 
.SH SYNOPSIS
\fIdraw.circle(\fBg\fR as <generic> IGraphics, 
\fBcenter\fR as <generic> PointF, 
\fBr\fR as double, 
\fBcolor\fR as any = "black", 
\fBborder\fR as any = "stroke: lightgray; stroke-width: 2px; stroke-dash: dash;");\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
