.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "layout.grid" "layout.grid"
.SH NAME
layout.grid \- 
.SH SYNOPSIS
\fIlayout.grid(\fBlayout\fR as integer, 
\fBmargin\fR as any = 0, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBlayout\fB \fR\- 
 should be two integer element which is indicate that 
 the element count on x and the element count on y.
. 
.PP
.PP
\fBmargin\fB \fR\- 
 the css internal padding data for each cell in the 
 generated grid layout.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
the canvas size and the entire padding is comes from the 
 current graphics device.
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
