.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-01-01 "legend" "legend"
.SH NAME
legend \- 
.SH SYNOPSIS
\fIlegend(\fBtitle\fR as string, 
\fBcolor\fR as any, 
\fBfont_style\fR as any = "font-style: normal; font-size: 12; font-family: Segoe UI;", 
\fBshape\fR as <integer> LegendStyles = [Circle]);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
