.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "legend" "legend"
.SH NAME
legend \- create a legend element
.SH SYNOPSIS
\fIlegend(\fBtitle\fR as string, 
\fBcolor\fR as any, 
\fBfont_style\fR as any = "font-style: normal; font-size: 12; font-family: Segoe UI;", 
\fBshape\fR as <integer> LegendStyles = [Circle]);\fR
.SH DESCRIPTION
.PP
create a legend element
.PP
.SH OPTIONS
.PP
\fBtitle$\fB \fR\- -. 
.PP
.PP
\fBcolor\fB \fR\- -. 
.PP
.PP
\fBfont_style\fB \fR\- -. 
.PP
.PP
\fBshape\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
