.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "measureString" "measureString"
.SH NAME
measureString \- 
.SH SYNOPSIS
\fImeasureString(\fBstr\fR as string, 
\fBfont\fR as any, 
\fBcanvas\fR as <generic> IGraphics = \fB<NULL>\fR);\fR
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
