.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "paddingString" "paddingString"
.SH NAME
paddingString \- create a valid css padding string
.SH SYNOPSIS
\fIpaddingString(\fBpadding\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a valid css padding string
.PP
.SH OPTIONS
.PP
\fBpadding\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
