.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-Jan "rasterHeatmap" "rasterHeatmap"
.SH NAME
rasterHeatmap \- 
.SH SYNOPSIS
\fIrasterHeatmap(\fBx\fR as any, 
\fBregion\fR as <generic> Rectangle = \fB<NULL>\fR, 
\fBdimSize\fR as any = \fB<NULL>\fR, 
\fBcolorName\fR as any = "jet", 
\fBgauss\fR as integer = 0, 
\fBcolorLevels\fR as integer = 255, 
\fBrasterBitmap\fR as boolean = FALSE, 
\fBfillRect\fR as boolean = TRUE, 
\fBstrict\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBregion\fB \fR\- -. 
.PP
.PP
\fBdimSize\fB \fR\- -. 
.PP
.PP
\fBcolorName\fB \fR\- -. 
.PP
.PP
\fBgauss\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
