.\" man page create by R# package system.
.TH GRAPHICS2D 1 2000-01-01 "scale" "scale"
.SH NAME
scale \- scale a numeric vector as the color value vector
.SH SYNOPSIS
\fIscale(\fBx\fR as double, 
\fBcolorSet\fR as any, 
\fBlevels\fR as integer = 25, 
\fBTrIQ\fR as double = 0.65, 
\fBzero\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
scale a numeric vector as the color value vector
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBcolorSet\fB \fR\- -. 
.PP
.PP
\fBlevels\fB \fR\- -. 
.PP
.PP
\fBTrIQ\fB \fR\- 
 set value negative or greater than 1 will be 
 disable the TrIQ scaler
. 
.PP
.SH VALUE
.PP
A color character vector in html code format
.PP
.SH SEE ALSO
graphics2D
.SH FILES
.PP
graphics.dll
.PP
