.\" man page create by R# package system.
.TH FTP 4 2000-01-01 "ftp.get" "ftp.get"
.SH NAME
ftp.get \- 
.SH SYNOPSIS
\fIftp.get(\fBftp\fR as <generic> FtpContext, 
\fBfile\fR as string, 
\fBsave\fR as string = "./", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ftp
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
