.\" man page create by R# package system.
.TH FTP 4 2000-01-01 "list.ftp_dirs" "list.ftp_dirs"
.SH NAME
list.ftp_dirs \- 
.SH SYNOPSIS
\fIlist.ftp_dirs(\fBftp\fR as <generic> FtpContext, 
\fBdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ftp
.SH FILES
.PP
R.web.dll
.PP
.SH COPYRIGHT
Copyright © Microsoft 2019
