.\" man page create by R# package system.
.TH STRINGS 1 2002-May "textlines" "textlines"
.SH NAME
textlines \- split text to lines
.SH SYNOPSIS
\fItextlines(\fBtext\fR as string, 
\fBtrim\fR as boolean = TRUE, 
\fBescape\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
split text to lines
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- -. 
.PP
.PP
\fBtrim\fB \fR\- -. 
.PP
.PP
\fBescape\fB \fR\- -. 
.PP
.SH SEE ALSO
strings
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
