.\" man page create by R# package system.
.TH FILTER 1 2000-Jan "emboss" "emboss"
.SH NAME
emboss \- 
.SH SYNOPSIS
\fIemboss(\fBimage\fR as <generic> Image, 
\fBdirection\fR as any = [1,1], 
\fBlighteness\fR as integer = 127, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
filter
.SH FILES
.PP
graphics.dll
.PP
