.\" man page create by R# package system.
.TH FILTER 1 2000-Jan "RTCP_gray" "RTCP_gray"
.SH NAME
RTCP_gray \- .NET Implement of Real-time Contrast Preserving Decolorization
.SH SYNOPSIS
\fIRTCP_gray(\fBimg\fR as <generic> Image);\fR
.SH DESCRIPTION
.PP
.NET Implement of Real-time Contrast Preserving Decolorization
.PP
.SH OPTIONS
.PP
\fBimg\fB \fR\- -. 
.PP
.SH DETAILS
.PP
https://github.com/IntPtrZero/RTCPRGB2Gray/tree/master
.PP
.SH SEE ALSO
filter
.SH FILES
.PP
graphics.dll
.PP
