.\" man page create by R# package system.
.TH LPSOLVE 1 2000-01-02 "linprog" "linprog"
.SH NAME
linprog \- 
.SH SYNOPSIS
\fIlinprog(\fBf\fR as <generic> vector, 
\fBA\fR as <generic> matrix, 
\fBb\fR as <generic> vector, 
\fBdirection\fR as <integer> OptimizationType = [MIN], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
lpSolve
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
