.\" man page create by R# package system.
.TH LPSOLVE 1 2000-Jan "lp" "lp"
.SH NAME
lp \- Linear and Integer Programming
.SH SYNOPSIS
\fIlp(\fBobjective\fR as <generic> Expression, 
\fBsubjective\fR as <generic> Expression[], 
\fBdirection\fR as <integer> OptimizationType = [MIN], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Linear and Integer Programming
.PP
.SH OPTIONS
.PP
\fBdirection\fB \fR\- Character string giving direction of optimization: "min" (default) or "max.". 
.PP
.PP
\fBobjective\fB \fR\- -. 
.PP
.PP
\fBsubjective\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
lpSolve
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
