.\" man page create by R# package system.
.TH LPSOLVE 1 2000-01-02 "lp.min" "lp.min"
.SH NAME
lp.min \- 
.SH SYNOPSIS
\fIlp.min(\fBobjective\fR as <generic> Expression, 
\fBsubjective\fR as <generic> Expression[], 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
lpSolve
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
