.\" man page create by R# package system.
.TH STATS 1 2000-Jan "aov" "aov"
.SH NAME
aov \- Fit an Analysis of Variance Model
.SH SYNOPSIS
\fIaov(\fBx\fR as <generic> dataframe, 
\fBformula\fR as <generic> FormulaExpression = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Fit an Analysis of Variance Model
 
 Fit an analysis of variance model by a call to lm for each stratum.
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
