.\" man page create by R# package system.
.TH STATS 1 2000-01-02 "CDF" "CDF"
.SH NAME
CDF \- Empirical Cumulative Distribution Function
.SH SYNOPSIS
\fICDF(\fBFUNC\fR as any, 
\fBrange\fR as any, 
\fBp0\fR as double = 0, 
\fBresolution\fR as integer = 50000, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Empirical Cumulative Distribution Function
 
 Compute an empirical cumulative distribution function
.PP
.SH OPTIONS
.PP
\fBFUNC\fB \fR\- -. 
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
