.\" man page create by R# package system.
.TH STATS 1 2000-Jan "CDF" "CDF"
.SH NAME
CDF \- Empirical Cumulative Distribution Function
.SH SYNOPSIS
\fICDF(\fBFUNC\fR as any, 
\fBrange\fR as any, 
\fBp0\fR as double = 0, 
\fBresolution\fR as integer = 50000, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Empirical Cumulative Distribution Function
 
 Compute an empirical cumulative distribution function
.PP
.SH OPTIONS
.PP
\fBFUNC\fB \fR\- function for run value integral, this function should 
 accept a number as parameter and produce new number as output.. 
.PP
.PP
\fBrange\fB \fR\- 
 the value range of the target function to do integral
. 
.PP
.PP
\fBp0\fB \fR\- 
 the y0 value for the integral
. 
.PP
.PP
\fBresolution\fB \fR\- 
 the RK4 integral algorithm resolution
. 
.PP
.SH VALUE
.PP
this function returns a tuple list object that contains the data slots:
 
 + \fBecdf\fR: the result value of the integral, a numeric scalar value
 + \fBx\fR: a numeric vector for x axis
 + \fBy\fR: a numeric vector for y axis
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
