.\" man page create by R# package system.
.TH STATS 1 2000-Jan "combin" "combin"
.SH NAME
combin \- calculates \fBC(n, k)\fR.
.SH SYNOPSIS
\fIcombin(\fBnumber\fR as integer, 
\fBnumber_chosen\fR as integer);\fR
.SH DESCRIPTION
.PP
calculates \fBC(n, k)\fR.
.PP
.SH OPTIONS
.PP
\fBnumber\fB \fR\- n. 
.PP
.PP
\fBnumber_chosen\fB \fR\- k. 
.PP
.SH DETAILS
.PP
https://en.wikipedia.org/wiki/Combination
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
