.\" man page create by R# package system.
.TH STATS 1 2000-01-02 "corr" "corr"
.SH NAME
corr \- matrix correlation
.SH SYNOPSIS
\fIcorr(\fBx\fR as <generic> dataframe, 
\fBspearman\fR as boolean = FALSE);\fR
.SH DESCRIPTION
.PP
matrix correlation
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- evaluate correlation for each row elements. 
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
