.\" man page create by R# package system.
.TH STATS 1 2000-Jan "filterMissing" "filterMissing"
.SH NAME
filterMissing \- set the NA, NaN, Inf value to the default value
.SH SYNOPSIS
\fIfilterMissing(\fBx\fR as any, 
\fBdefault\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set the NA, NaN, Inf value to the default value
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a numeric vector or a dataframe object of all elements in numeric mode.
. 
.PP
.PP
\fBdefault\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
