.\" man page create by R# package system.
.TH STATS 1 2000-Jan "level" "level"
.SH NAME
level \- get quantile levels
.SH SYNOPSIS
\fIlevel(\fBq\fR as <generic> QuantileQuery, 
\fBlevel\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get quantile levels
.PP
.SH OPTIONS
.PP
\fBq\fB \fR\- -. 
.PP
.PP
\fBlevel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
