.\" man page create by R# package system.
.TH STATS 1 2000-Jan "lowess" "lowess"
.SH NAME
lowess \- 
.SH SYNOPSIS
\fIlowess(\fBx\fR as any, 
\fBf\fR as double = 0.6666666666666666, 
\fBnsteps\fR as integer = 3, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
