.\" man page create by R# package system.
.TH STATS 1 2000-Jan "spline" "spline"
.SH NAME
spline \- Interpolating Splines
.SH SYNOPSIS
\fIspline(\fBdata\fR as any, 
\fBalgorithm\fR as <integer> SplineAlgorithms = [BSpline], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Interpolating Splines
.PP
.SH SEE ALSO
stats
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
