.\" man page create by R# package system.
.TH NETCDF.UTILS 1 2000-01-01 "attr" "attr"
.SH NAME
attr \- get attribute data of a cdf variable
.SH SYNOPSIS
\fIattr(\fBfile\fR as any, 
\fBname\fR as string, 
\fBlist\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get attribute data of a cdf variable
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
netCDF.utils
.SH FILES
.PP
base.dll
.PP
