.\" man page create by R# package system.
.TH NETCDF.UTILS 1 2000-01-01 "dataframe" "dataframe"
.SH NAME
dataframe \- read multiple variable symbols in the given cdf file and then create as dataframe object
.SH SYNOPSIS
\fIdataframe(\fBcdf\fR as <generic> netCDFReader, 
\fBsymbols\fR as string, 
\fBrownames\fR as string);\fR
.SH DESCRIPTION
.PP
read multiple variable symbols in the given cdf file and then create as dataframe object
.PP
.SH OPTIONS
.PP
\fBcdf\fB \fR\- -. 
.PP
.PP
\fBsymbols\fB \fR\- the symbol will be used as the columns in the generated dataframe. 
.PP
.SH SEE ALSO
netCDF.utils
.SH FILES
.PP
base.dll
.PP
