.\" man page create by R# package system.
.TH NETCDF.UTILS 1 2000-Jan "getValue" "getValue"
.SH NAME
getValue \- get value from variable
.SH SYNOPSIS
\fIgetValue(\fBvar\fR as <generic> variable);\fR
.SH DESCRIPTION
.PP
get value from variable
.PP
.SH OPTIONS
.PP
\fBvar\fB \fR\- -. 
.PP
.SH SEE ALSO
netCDF.utils
.SH FILES
.PP
base.dll
.PP
