.\" man page create by R# package system.
.TH NETCDF.UTILS 1 2000-Jan "open.netCDF" "open.netCDF"
.SH NAME
open.netCDF \- open a netCDF data file
.SH SYNOPSIS
\fIopen.netCDF(\fBfile\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open a netCDF data file
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
netCDF.utils
.SH FILES
.PP
base.dll
.PP
