.\" man page create by R# package system.
.TH RUST 1 2002-May "dyn.load" "dyn.load"
.SH NAME
dyn.load \- Foreign Function Interface
.SH SYNOPSIS
\fIdyn.load(\fBx\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Foreign Function Interface
 
 Load or unload DLLs (also known as shared objects), and test whether a 
 C function or Fortran subroutine is available.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a character string giving the pathname to a DLL, also known as a dynamic 
 shared object. (See ‘Details’ for what these terms mean.)
. 
.PP
.SH SEE ALSO
rust
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
