.\" man page create by R# package system.
.TH JSON 4 2000-Jan "writeBSON" "writeBSON"
.SH NAME
writeBSON \- save any R object into BSON stream data
.SH SYNOPSIS
\fIwriteBSON(\fBobj\fR as any, 
\fBfile\fR as any = \fB<NULL>\fR, 
\fBmaskReadonly\fR as boolean = FALSE, 
\fBenumToStr\fR as boolean = TRUE, 
\fBunixTimestamp\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save any R object into BSON stream data
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- 
 the file resource that used for save the BSON data, if this parameter is empty, then
 a binary data stream that contains the BSON data will be returned.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
JSON
.SH FILES
.PP
base.dll
.PP
.SH AUTHOR
Written by \fBi@xieguigang.me\fR
