.\" man page create by R# package system.
.TH SYMBOLIC 2 2000-Jan "gp_fit" "gp_fit"
.SH NAME
gp_fit \- 
.SH SYNOPSIS
\fIgp_fit(\fBx\fR as double, 
\fBy\fR as double, 
\fBsymbols\fR as any = ["1","2","12","E","PI","Tau","Sin","Cos","Log","Exp","Pow"], 
\fBthreshold\fR as double = 0.05, 
\fBepochs\fR as integer = 10, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
symbolic
.SH FILES
.PP
Rlapack.dll
.PP
.SH COPYRIGHT
GPL3
