.\" man page create by R# package system.
.TH HDS 1 2000-Jan "createStream" "createStream"
.SH NAME
createStream \- Create a new data pack stream object, this function will clear up the data that sotre in the target **`file`**!
.SH SYNOPSIS
\fIcreateStream(\fBfile\fR as string, 
\fBmeta_size\fR as integer = 4194304);\fR
.SH DESCRIPTION
.PP
Create a new data pack stream object, this function will clear up the data that sotre in the target **`file`**!
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBmeta_size\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
