.\" man page create by R# package system.
.TH HDS 1 2000-Jan "extract_files" "extract_files"
.SH NAME
extract_files \- Extract the files inside the HDS pack to a specific filesystem environment
.SH SYNOPSIS
\fIextract_files(\fBpack\fR as <generic> StreamPack, 
\fBfs\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract the files inside the HDS pack to a specific filesystem environment
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBfs\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
