.\" man page create by R# package system.
.TH HDS 1 2000-Jan "getData" "getData"
.SH NAME
getData \- get a stream in readonly mode for parse data
.SH SYNOPSIS
\fIgetData(\fBpack\fR as <generic> StreamPack, 
\fBfile\fR as <generic> StreamBlock);\fR
.SH DESCRIPTION
.PP
get a stream in readonly mode for parse data
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
