.\" man page create by R# package system.
.TH HDS 1 2000-Jan "getText" "getText"
.SH NAME
getText \- Read a specific text data from a HDS stream pack
.SH SYNOPSIS
\fIgetText(\fBpack\fR as <generic> StreamPack, 
\fBfileName\fR as string, 
\fBencoding\fR as any = "utf8", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Read a specific text data from a HDS stream pack
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBfileName\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
