.\" man page create by R# package system.
.TH HDS 1 2000-Jan "openStream" "openStream"
.SH NAME
openStream \- Open a HDS stream pack file, this function will create a new file is the given **`file`** is not exists
.SH SYNOPSIS
\fIopenStream(\fBfile\fR as any, 
\fBreadonly\fR as boolean = FALSE, 
\fBallowCreate\fR as boolean = FALSE, 
\fBmeta_size\fR as integer = 8388608, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Open a HDS stream pack file, this function will create a new file is the given **`file`** is not exists
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBreadonly\fB \fR\- Indicates that the file content just used for readonly, not allow updates?. 
.PP
.PP
\fBallowCreate\fB \fR\- -. 
.PP
.PP
\fBmeta_size\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
