.\" man page create by R# package system.
.TH HDS 1 2000-Jan "saveFile" "saveFile"
.SH NAME
saveFile \- write data to a HDS stream pack file
.SH SYNOPSIS
\fIsaveFile(\fBhds\fR as <generic> StreamPack, 
\fBfileName\fR as string, 
\fBdata\fR as any);\fR
.SH DESCRIPTION
.PP
write data to a HDS stream pack file
.PP
.SH OPTIONS
.PP
\fBhds\fB \fR\- -. 
.PP
.PP
\fBfileName\fB \fR\- -. 
.PP
.PP
\fBdata\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
