.\" man page create by R# package system.
.TH HDS 1 2000-Jan "tree" "tree"
.SH NAME
tree \- Get the filesystem tree inside the given HDS pack file
.SH SYNOPSIS
\fItree(\fBpack\fR as <generic> StreamPack, 
\fBshowReadme\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
Get the filesystem tree inside the given HDS pack file
.PP
.SH OPTIONS
.PP
\fBpack\fB \fR\- -. 
.PP
.PP
\fBshowReadme\fB \fR\- -. 
.PP
.SH SEE ALSO
HDS
.SH FILES
.PP
base.dll
.PP
