.\" man page create by R# package system.
.TH BASE 4 2000-Jan "parseTtl" "parseTtl"
.SH NAME
parseTtl \- parse the RDF Turtle document
.SH SYNOPSIS
\fIparseTtl(\fBfile\fR as any, 
\fBlazy\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse the RDF Turtle document
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
base
.SH FILES
.PP
base.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
