.\" man page create by R# package system.
.TH SET 1 2002-May "count" "count"
.SH NAME
count \- is a \fBtable\fR liked function for count string occurance number
.SH SYNOPSIS
\fIcount(\fBstr\fR as <generic> Array);\fR
.SH DESCRIPTION
.PP
is a \fBtable\fR liked function for count string occurance number
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- 
 A character vector that may contains the
 duplicated string value
. 
.PP
.SH SEE ALSO
set
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
