.\" man page create by R# package system.
.TH SET 1 2002-May "jaccard" "jaccard"
.SH NAME
jaccard \- The Jaccard Index, also known as the Jaccard similarity coefficient,
.SH SYNOPSIS
\fIjaccard(\fBx\fR as <generic> Array, 
\fBy\fR as <generic> Array, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
The Jaccard Index, also known as the Jaccard similarity coefficient, 
 is a statistic used in understanding the similarities between sample 
 sets. The measurement emphasizes similarity between finite sample 
 sets, and is formally defined as the size of the intersection divided
 by the size of the union of the sample sets.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
set
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
