.\" man page create by R# package system.
.TH SET 1 2002-May "setdiff" "setdiff"
.SH NAME
setdiff \- setdiff: Set Difference of Subsets
.SH SYNOPSIS
\fIsetdiff(\fBx\fR as <generic> Array, 
\fBy\fR as <generic> Array, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
setdiff: Set Difference of Subsets
.PP
.SH SEE ALSO
set
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
