.\" man page create by R# package system.
.TH SET 1 2002-May "unset" "unset"
.SH NAME
unset \- unset — Unset the feature slots value from a given variable
.SH SYNOPSIS
\fIunset(\fBx\fR as any, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
unset — Unset the feature slots value from a given variable
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 should be a tuple list object or dataframe object
. 
.PP
.PP
\fBargs\fB \fR\- the features names to deletes from the given object **`x`**.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
the orginal object will be modified by this function
.PP
.SH SEE ALSO
set
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
