.\" man page create by R# package system.
.TH UMAP 1 2000-Jan "as.graph" "as.graph"
.SH NAME
as.graph \- Extract the umap graph
.SH SYNOPSIS
\fIas.graph(\fBumap\fR as <generic> Umap, 
\fBlabels\fR as any, 
\fBgroups\fR as any = \fB<NULL>\fR, 
\fBthreshold\fR as double = 0, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Extract the umap graph
.PP
.SH OPTIONS
.PP
\fBumap\fB \fR\- -. 
.PP
.PP
\fBlabels\fB \fR\- -. 
.PP
.PP
\fBgroups\fB \fR\- -. 
.PP
.PP
\fBthreshold\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
umap
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
