.\" man page create by R# package system.
.TH VISUALIZER 1 2000-01-01 "setColors" "setColors"
.SH NAME
setColors \- set color by node group
.SH SYNOPSIS
\fIsetColors(\fBg\fR as <generic> NetworkGraph, 
\fBtype\fR as string, 
\fBcolor\fR as any);\fR
.SH DESCRIPTION
.PP
set color by node group
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBtype$\fB \fR\- -. 
.PP
.PP
\fBcolor$\fB \fR\- -. 
.PP
.SH SEE ALSO
visualizer
.SH FILES
.PP
igraph.dll
.PP
