.\" man page create by R# package system.
.TH BASE 1 2002-May "append" "append"
.SH NAME
append \- Vector Merging
.SH SYNOPSIS
\fIappend(\fBx\fR as any, 
\fBvalues\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Vector Merging
 
 Add elements to a vector.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- the vector the values are to be appended to.. 
.PP
.PP
\fBvalues\fB \fR\- to be included in the modified vector.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
A vector containing the values in x with the elements of values 
 appended after the specified element of x.
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
