.\" man page create by R# package system.
.TH BASE 1 2002-May "date" "date"
.SH NAME
date \- System Date and Time
.SH SYNOPSIS
\fIdate(\fBstr\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
System Date and Time
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- 
 this parameter also can accept the unix timestamp.
. 
.PP
.SH VALUE
.PP
Returns a character string of the current system date and time.
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
