.\" man page create by R# package system.
.TH BASE 1 2002-May "dQuote" "dQuote"
.SH NAME
dQuote \- Quote Text
.SH SYNOPSIS
\fIdQuote(\fBx\fR as string, 
\fBq\fR as any = CALL "GETOPTION"("USEFANCYQUOTES"));\fR
.SH DESCRIPTION
.PP
Quote Text
 
 Single or double quote text by combining with appropriate 
 single or double left and right quotation marks.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an R object, to be coerced to a character vector.. 
.PP
.PP
\fBq\fB \fR\- the kind of quotes to be used, see ‘Details’.. 
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
