.\" man page create by R# package system.
.TH BASE 1 2002-May "is.data.frame" "is.data.frame"
.SH NAME
is.data.frame \- Coerce to a Data Frame
.SH SYNOPSIS
\fIis.data.frame(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Coerce to a Data Frame
 
 Functions to check if an object is a data frame, or coerce it 
 if possible.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- any R object.. 
.PP
.SH VALUE
.PP
is.data.frame returns TRUE if its argument is a data frame 
 (that is, has "data.frame" amongst its classes) and FALSE 
 otherwise.
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
