.\" man page create by R# package system.
.TH BASE 1 2002-May "is.function" "is.function"
.SH NAME
is.function \- Is an Object of Type (Primitive) Function?
.SH SYNOPSIS
\fIis.function(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Is an Object of Type (Primitive) Function?
 
 Checks whether its argument is a (primitive) function.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- an R object.. 
.PP
.SH VALUE
.PP
TRUE if x is a (primitive) function, and FALSE otherwise.
.PP
.SH DETAILS
.PP
is.primitive(x) tests if x is a primitive function, i.e, if typeof(x) is either "builtin" or "special".
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
