.\" man page create by R# package system.
.TH BASE 1 2002-May "is.list" "is.list"
.SH NAME
is.list \- Lists – Generic and Dotted Pairs
.SH SYNOPSIS
\fIis.list(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Lists – Generic and Dotted Pairs
 
 Functions to construct, coerce and check for both kinds of R lists.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 object to be coerced or tested.
. 
.PP
.SH VALUE
.PP
is.list returns TRUE if and only if its argument is a list or 
 a pairlist of length > 0. is.pairlist returns TRUE if and only 
 if the argument is a pairlist or NULL (see below).
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
