.\" man page create by R# package system.
.TH BASE 1 2002-May "rep.int" "rep.int"
.SH NAME
rep.int \- 
.SH SYNOPSIS
\fIrep.int(\fBx\fR as any, 
\fBtimes\fR as integer, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBtimes\fB \fR\- an integer-valued vector giving the (non-negative) 
 number of times to repeat each element if of length length(x), or to
 repeat the whole vector if of length 1. Negative or NA values are an 
 error. A double vector is accepted, other inputs being coerced to an
 integer or double vector.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
