.\" man page create by R# package system.
.TH BASE 1 2002-May "rep_len" "rep_len"
.SH NAME
rep_len \- 
.SH SYNOPSIS
\fIrep_len(\fBx\fR as any, 
\fBlength_out\fR as integer, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBlength_out\fB \fR\- non-negative integer. The desired 
 length of the output vector. Other inputs will be coerced to 
 a double vector and the first element taken. Ignored if NA 
 or invalid.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
base
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
