.\" man page create by R# package system.
.TH XGBOOST 1 2000-Jan "predict" "predict"
.SH NAME
predict \- do predictions
.SH SYNOPSIS
\fIpredict(\fBgbm\fR as <generic> GBM, 
\fBdata\fR as <generic> TestData);\fR
.SH DESCRIPTION
.PP
do predictions
.PP
.SH OPTIONS
.PP
\fBgbm\fB \fR\- -. 
.PP
.PP
\fBdata\fB \fR\- -. 
.PP
.SH SEE ALSO
xgboost
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
