.\" man page create by R# package system.
.TH XGBOOST 1 2000-Jan "serialize" "serialize"
.SH NAME
serialize \- save model
.SH SYNOPSIS
\fIserialize(\fBmodel\fR as <generic> GBM);\fR
.SH DESCRIPTION
.PP
save model
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.SH SEE ALSO
xgboost
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
