.\" man page create by R# package system.
.TH UTILS 4 2000-Jan "load.csv" "load.csv"
.SH NAME
load.csv \- load csv as a .NET CLR object vector
.SH SYNOPSIS
\fIload.csv(\fBfile\fR as any, 
\fBtype\fR as any, 
\fBencoding\fR as any = "unknown", 
\fBtsv\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
load csv as a .NET CLR object vector
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBtype\fB \fR\- 
 the object type value, and it should be one of the:
 
 1. class name from the @\fBT:SMRUCC.Rsharp.Runtime.Interop.RTypeExportAttribute\fR
 2. .NET CLR @\fBT:System.Type\fR value
 3. R-sharp @\fBT:SMRUCC.Rsharp.Runtime.Interop.RType\fR value
 4. R-sharp primitive @\fBT:SMRUCC.Rsharp.Runtime.Components.TypeCodes\fR value
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
base.dll
.PP
