.\" man page create by R# package system.
.TH UTILS 4 2000-Jan "readRData" "readRData"
.SH NAME
readRData \- read \fB*.rda\fR data file which is saved from R environment.
.SH SYNOPSIS
\fIreadRData(\fBfile\fR as string);\fR
.SH DESCRIPTION
.PP
read \fB*.rda\fR data file which is saved from R environment.
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
base.dll
.PP
