import {stringr} from "base";

var assem = stringr.shortest_common_superstring([
	"AACAAATGAGACGCTGTGCAATTGCTGA",
	"AACAAATGAGACGCTGTGCAATTGCTGA",
	"CAAATGAGACGCTGTGCAATTGCTGAGT",
	"ATGAGACGCTGTGCAATTGCTGAGTACC",
	"CTGTGCAATTGCTGAGTACCGTAGGTAG",
	"CTGTGCAATTGCTGAGTACCGTAGGTAG"
])

console.log(assem)
console.table(assem)