.\" man page create by R# package system.
.TH ETC 1 2002-May "cultureInfo" "cultureInfo"
.SH NAME
cultureInfo \- Initializes a new instance of the System.Globalization.CultureInfo class based
.SH SYNOPSIS
\fIcultureInfo(\fBcultureName\fR as string = "en-US");\fR
.SH DESCRIPTION
.PP
Initializes a new instance of the System.Globalization.CultureInfo class based
 on the culture specified by name.
.PP
.SH OPTIONS
.PP
\fBcultureName\fB \fR\- A predefined System.Globalization.CultureInfo name,
 System.Globalization.CultureInfo.Name of an existing System.Globalization.CultureInfo, 
 Or Windows-only culture name. name Is Not case-sensitive.. 
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
