.\" man page create by R# package system.
.TH ETC 1 2002-May "Sys.getlocale" "Sys.getlocale"
.SH NAME
Sys.getlocale \- Provides information about a specific culture (called a locale for unmanaged
.SH SYNOPSIS
\fISys.getlocale();\fR
.SH DESCRIPTION
.PP
Provides information about a specific culture (called a locale for unmanaged
 code development). The information includes the names for the culture, the writing
 system, the calendar used, the sort order of strings, and formatting for dates
 and numbers.
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
