.\" man page create by R# package system.
.TH ETC 1 2002-May "Sys.getenv" "Sys.getenv"
.SH NAME
Sys.getenv \- Get Environment Variables
.SH SYNOPSIS
\fISys.getenv(\fBx\fR as string);\fR
.SH DESCRIPTION
.PP
Get Environment Variables
 
 \fBSys.getenv\fR obtains the values of the environment variables.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a character vector, or NULL.
. 
.PP
.SH SEE ALSO
etc
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
