.\" man page create by R# package system.
.TH RINTEROP 1 2002-May ".Load" ".Load"
.SH NAME
.Load \- imports VB.NET namespace
.SH SYNOPSIS
\fI.Load(\fBnamespace\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
imports VB.NET namespace
.PP
.SH OPTIONS
.PP
\fB[namespace]\fB \fR\- 
 only import of the instance method from 
 the given types in the target namespace 
 value.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
Rinterop
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
