.\" man page create by R# package system.
.TH GRDEVICES 4 2000-Jan "colors" "colors"
.SH NAME
colors \- get color set
.SH SYNOPSIS
\fIcolors(\fBterm\fR as any, 
\fBn\fR as integer = 256, 
\fBcharacter\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get color set
.PP
.SH OPTIONS
.PP
\fBterm\fB \fR\- the color set name, if the parameter value 
 is an image data, then this function will try to extract the
 theme colors from it.. 
.PP
.PP
\fBn\fB \fR\- 
 number of colors from the given color set(apply cubic 
 spline for the color sequence), negative value or 
 ZERO means no cubic spline on the color sequence.
. 
.PP
.PP
\fBcharacter\fB \fR\- 
 function returns a color object sequence 
 or html color code string vector if this parameter 
 value is set to \fBTRUE\fR
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
graphics.dll
.PP
