.\" man page create by R# package system.
.TH GRDEVICES 4 2000-Jan "graphics" "graphics"
.SH NAME
graphics \- save the graphics plot object as image file
.SH SYNOPSIS
\fIgraphics(\fBgraphics\fR as any, 
\fBfile\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
save the graphics plot object as image file
.PP
.SH OPTIONS
.PP
\fBgraphics\fB \fR\- a graphics plot object. 
.PP
.PP
\fBfile\fB \fR\- the file path for save the image file. 
 (if this file path parameter is nothing, then the resulted 
 image object will be flush to the standard output stream 
 of R# environment.)
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
graphics.dll
.PP
