.\" man page create by R# package system.
.TH GRDEVICES 4 2000-Jan "register.color_palette" "register.color_palette"
.SH NAME
register.color_palette \- register a custom color palette to the graphics system
.SH SYNOPSIS
\fIregister.color_palette(\fBname\fR as string, 
\fBcolors\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
register a custom color palette to the graphics system
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- -. 
.PP
.PP
\fBcolors\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
graphics.dll
.PP
