.\" man page create by R# package system.
.TH GRDEVICES 4 2000-Jan "svg" "svg"
.SH NAME
svg \- Cairographics-based SVG, PDF and PostScript Graphics Devices
.SH SYNOPSIS
\fIsvg(\fBimage\fR as any = \fB<NULL>\fR, 
\fBfile\fR as any = \fB<NULL>\fR, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Cairographics-based SVG, PDF and PostScript Graphics Devices
 
 Graphics devices for SVG, PDF and PostScript 
 graphics files using the cairo graphics API.
.PP
.SH OPTIONS
.PP
\fBimage\fB \fR\- -. 
.PP
.PP
\fBfile\fB \fR\- -. 
.PP
.SH SEE ALSO
grDevices
.SH FILES
.PP
graphics.dll
.PP
