.\" man page create by R# package system.
.TH STYLER 1 2000-01-01 "color" "color"
.SH NAME
color \- get/set node or edge color style
.SH SYNOPSIS
\fIcolor(\fBg\fR as any, 
\fBval\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get/set node or edge color style
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBval\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
styler
.SH FILES
.PP
igraph.dll
.PP
