.\" man page create by R# package system.
.TH STYLER 1 2000-01-01 "size" "size"
.SH NAME
size \- set or get node size data
.SH SYNOPSIS
\fIsize(\fBv\fR as <generic> V, 
\fBval\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set or get node size data
.PP
.SH OPTIONS
.PP
\fBv\fB \fR\- -. 
.PP
.SH SEE ALSO
styler
.SH FILES
.PP
igraph.dll
.PP
