.\" man page create by R# package system.
.TH STYLER 1 2000-Jan "width" "width"
.SH NAME
width \- set or get edge pen width
.SH SYNOPSIS
\fIwidth(\fBe\fR as <generic> E, 
\fBval\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
set or get edge pen width
.PP
.SH OPTIONS
.PP
\fBe\fB \fR\- -. 
.PP
.PP
\fBval\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
styler
.SH FILES
.PP
igraph.dll
.PP
