.\" man page create by R# package system.
.TH DATAFRAMEBASE 1 2002-May "aggregate" "aggregate"
.SH NAME
aggregate \- 
.SH SYNOPSIS
\fIaggregate(\fBx\fR as <generic> dataframe, 
\fBexpr\fR as <generic> Expression, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
dataframeBase
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
