.\" man page create by R# package system.
.TH DATAFRAMEBASE 1 2002-May "colSums" "colSums"
.SH NAME
colSums \- colSums: Form Row and Column Sums and Means
.SH SYNOPSIS
\fIcolSums(\fBx\fR as <generic> dataframe, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
colSums: Form Row and Column Sums and Means
 
 Form row and column sums and means for numeric arrays (or data frames).
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 an array of two or more dimensions, containing numeric, 
 complex, integer or logical values, or a numeric data 
 frame. For .colSums() etc, a numeric, integer or logical 
 matrix (or vector of length m * n).
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
dataframeBase
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
