.\" man page create by R# package system.
.TH DATAFRAMEBASE 1 2002-May "rename" "rename"
.SH NAME
rename \- renames the dataframe object its specific column fields
.SH SYNOPSIS
\fIrename(\fBx\fR as <generic> dataframe, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
renames the dataframe object its specific column fields
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBrenames\fB \fR\- 
 a collection of name mapping lambda, liked: \fBa -> b\fR
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function will returns nothing if the given dataframe object is nothing
.PP
.SH SEE ALSO
dataframeBase
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
