.TH EXPORT 1 2023-Mar "" "export"
.SH NAME
export \- export(r,
    <i>a</i> = <span style='color: blue;'>FALSE</span>,
    <i>b</i> = 333,
    <i>d</i> = hello)
.SH SYNOPSIS
\fIexport(r,
    <i>a</i> = <span style='color: blue;'>FALSE</span>,
    <i>b</i> = 333,
    <i>d</i> = hello)\fR
.SH OPTIONS
.PP
\fBr\fB \fR\- . 
.PP
.PP
\fBa\fB \fR\- FALSE. 
.PP
.PP
\fBb\fB \fR\- 333. 
.PP
.PP
\fBd\fB \fR\- hello. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export at export.R:line 2
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
