.\" man page create by R# package system.
.TH MATH 2 2000-01-02 "diff_entropy" "diff_entropy"
.SH NAME
diff_entropy \- 
.SH SYNOPSIS
\fIdiff_entropy(\fBx\fR as double, 
\fBy\fR as double);\fR
.SH SEE ALSO
math
.SH FILES
.PP
Rlapack.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
