.\" man page create by R# package system.
.TH HUMANREADABLE 1 2002-May "byte_size" "byte_size"
.SH NAME
byte_size \- convert byte number into human readable size string
.SH SYNOPSIS
\fIbyte_size(\fBbytes\fR as double);\fR
.SH DESCRIPTION
.PP
convert byte number into human readable size string
.PP
.SH OPTIONS
.PP
\fBbytes\fB \fR\- -. 
.PP
.SH SEE ALSO
humanReadable
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
