.\" man page create by R# package system.
.TH HUMANREADABLE 1 2002-May "splitParagraph" "splitParagraph"
.SH NAME
splitParagraph \- split a given text data into multiple lines
.SH SYNOPSIS
\fIsplitParagraph(\fBtext\fR as string, 
\fBlen\fR as integer = 80, 
\fBdelimiters\fR as string = ";:,.-_&*!+'~	 ", 
\fBfloatChars\fR as integer = 6);\fR
.SH DESCRIPTION
.PP
split a given text data into multiple lines
.PP
.SH OPTIONS
.PP
\fBtext\fB \fR\- -. 
.PP
.PP
\fBlen\fB \fR\- -. 
.PP
.SH SEE ALSO
humanReadable
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
