.\" man page create by R# package system.
.TH HUMANREADABLE 1 2002-May "time_span" "time_span"
.SH NAME
time_span \- cast timespan value to human readable string
.SH SYNOPSIS
\fItime_span(\fBspans\fR as <generic> TimeSpan[], 
\fBshow_ms\fR as boolean = TRUE);\fR
.SH DESCRIPTION
.PP
cast timespan value to human readable string
.PP
.SH OPTIONS
.PP
\fBspans\fB \fR\- -. 
.PP
.SH SEE ALSO
humanReadable
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
