.\" man page create by R# package system.
.TH VAE 1 2000-Jan "vae" "vae"
.SH NAME
vae \- create vae training algorithm
.SH SYNOPSIS
\fIvae(\fBdims\fR as any, 
\fBlatent_dims\fR as integer = 100, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create vae training algorithm
.PP
.SH SEE ALSO
VAE
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
