.\" man page create by R# package system.
.TH CLUSTERING 2 2000-Jan "cluster.groups" "cluster.groups"
.SH NAME
cluster.groups \- get cluster result data
.SH SYNOPSIS
\fIcluster.groups(\fBx\fR as any, 
\fBlabels\fR as any = \fB<NULL>\fR, 
\fBlabelclass_tuple\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get cluster result data
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBlabels\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
