.\" man page create by R# package system.
.TH CLUSTERING 2 2000-Jan "clusters" "clusters"
.SH NAME
clusters \- get or set the cluster class labels
.SH SYNOPSIS
\fIclusters(\fBx\fR as any, 
\fBclass\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get or set the cluster class labels
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fB[class]\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
