.\" man page create by R# package system.
.TH CLUSTERING 1 2000-01-01 "cmeans" "cmeans"
.SH NAME
cmeans \- 
.SH SYNOPSIS
\fIcmeans(\fBdataset\fR as <generic> Object, 
\fBcenters\fR as integer = 3, 
\fBfuzzification\fR as double = 2, 
\fBthreshold\fR as double = 0.001, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
Copyright ©  2020
