.\" man page create by R# package system.
.TH CLUSTERING 2 2000-Jan "dbscan_objects" "dbscan_objects"
.SH NAME
dbscan_objects \- find objects from a given set of 2d points
.SH SYNOPSIS
\fIdbscan_objects(\fBpoints\fR as any, 
\fBsampleSize\fR as integer = 50, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
find objects from a given set of 2d points
.PP
.SH OPTIONS
.PP
\fBpoints\fB \fR\- -. 
.PP
.PP
\fBsampleSize\fB \fR\- 
 sample size for auto check best distance 
 threshold value for the object detection.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
