.\" man page create by R# package system.
.TH CLUSTERING 2 2000-Jan "gmm" "gmm"
.SH NAME
gmm \- Construct a Gaussian Mixture Model with specific n components
.SH SYNOPSIS
\fIgmm(\fBx\fR as any, 
\fBcomponents\fR as integer = 3, 
\fBthreshold\fR as double = 1E-07, 
\fBstrict\fR as boolean = TRUE, 
\fBverbose\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Construct a Gaussian Mixture Model with specific n components
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
