.\" man page create by R# package system.
.TH CLUSTERING 2 2000-Jan "gmm.predict_proba" "gmm.predict_proba"
.SH NAME
gmm.predict_proba \- 
.SH SYNOPSIS
\fIgmm.predict_proba(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
clustering
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
