.\" man page create by R# package system.
.TH DEVTOOLS 1 2002-May "flash_load" "flash_load"
.SH NAME
flash_load \- Load R script in directory
.SH SYNOPSIS
\fIflash_load(\fBdir\fR as string = CALL "GETWD"(), 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Load R script in directory
 
 Load all of the R script in a given working directory,
 by default is load all script in current directory.
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- The script source directory, by default is current workspace.. 
.PP
.SH SEE ALSO
devtools
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
