.\" man page create by R# package system.
.TH DEVTOOLS 1 2002-May "profiler.fetch" "profiler.fetch"
.SH NAME
profiler.fetch \- get performance profile data
.SH SYNOPSIS
\fIprofiler.fetch([\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get performance profile data
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
devtools
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
