.\" man page create by R# package system.
.TH DEVTOOLS 1 2002-May "raiseException" "raiseException"
.SH NAME
raiseException \- this function will throw a .NET exception for run exception handler demo test
.SH SYNOPSIS
\fIraiseException(\fBmessage\fR as string);\fR
.SH DESCRIPTION
.PP
this function will throw a .NET exception for run exception handler demo test
.PP
.SH OPTIONS
.PP
\fBmessage\fB \fR\- -. 
.PP
.SH SEE ALSO
devtools
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
