.\" man page create by R# package system.
.TH APPLYS 1 2002-May "parLapply" "parLapply"
.SH NAME
parLapply \- Parallel version of \fBlapply\fR.
.SH SYNOPSIS
\fIparLapply(\fBx\fR as list, 
\fBFUN\fR as any, 
\fBgroup\fR as integer = -1, 
\fBn_threads\fR as integer = -1, 
\fBverbose\fR as boolean = \fB<NULL>\fR, 
\fBnames\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Parallel version of \fBlapply\fR.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBFUN\fB \fR\- -. 
.PP
.PP
\fBgroup\fB \fR\- -. 
.PP
.PP
\fBn_threads\fB \fR\- -. 
.PP
.PP
\fBverbose\fB \fR\- -. 
.PP
.PP
\fBnames\fB \fR\- 
 Set new names to the result list, the size of this parameter
 should be equals to the size of the original input sequence 
 size.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
applys
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
