.\" man page create by R# package system.
.TH APPLYS 1 2002-May "parSapply" "parSapply"
.SH NAME
parSapply \- parallel sapply
.SH SYNOPSIS
\fIparSapply(\fBX\fR as any, 
\fBFUN\fR as any, 
\fBgroup\fR as integer = -1, 
\fBn_threads\fR as integer = -1, 
\fBverbose\fR as boolean = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parallel sapply
.PP
.SH SEE ALSO
applys
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
