.\" man page create by R# package system.
.TH BUFFER 4 2000-Jan "integer" "integer"
.SH NAME
integer \- apply bit convert of the bytes stream data as integer numbers
.SH SYNOPSIS
\fIinteger(\fBstream\fR as any, 
\fBnetworkOrder\fR as boolean = FALSE, 
\fBsizeOf\fR as integer = 32, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
apply bit convert of the bytes stream data as integer numbers
.PP
.SH OPTIONS
.PP
\fBstream\fB \fR\- -. 
.PP
.PP
\fBnetworkOrder\fB \fR\- -. 
.PP
.PP
\fBsizeOf\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
buffer
.SH FILES
.PP
base.dll
.PP
