.\" man page create by R# package system.
.TH BUFFER 4 2000-01-01 "string" "string"
.SH NAME
string \- char to string or raw bytes to string
.SH SYNOPSIS
\fIstring(\fBraw\fR as any, 
\fBencoding\fR as <integer> Encodings = [UTF8], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
char to string or raw bytes to string
.PP
.SH OPTIONS
.PP
\fBraw\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
buffer
.SH FILES
.PP
base.dll
.PP
