.\" man page create by R# package system.
.TH BUFFER 4 2000-Jan "zlib_stream" "zlib_stream"
.SH NAME
zlib_stream \- zip compression of stream data
.SH SYNOPSIS
\fIzlib_stream(\fBstream\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
zip compression of stream data
.PP
.SH OPTIONS
.PP
\fBstream\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
buffer
.SH FILES
.PP
base.dll
.PP
