.\" man page create by R# package system.
.TH FILE 1 2002-May "basename" "basename"
.SH NAME
basename \- removes all of the path up to and including the last path separator (if any).
.SH SYNOPSIS
\fIbasename(\fBfileNames\fR as string, 
\fBwithExtensionName\fR as boolean = FALSE, 
\fBstrict\fR as any = CALL "AS.LOGICAL"(CALL "GETOPTION"("STRICT")), 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
removes all of the path up to and including the last path separator (if any).
.PP
.SH OPTIONS
.PP
\fBfileNames\fB \fR\- character vector, containing path names.. 
.PP
.PP
\fBwithExtensionName\fB \fR\- 
 option for config keeps the extension suffix in the name or not, 
 removes the file suffix name by default.
. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
