.\" man page create by R# package system.
.TH FILE 1 2002-May "bytes" "bytes"
.SH NAME
bytes \- create a in-memory byte stream object
.SH SYNOPSIS
\fIbytes(\fBbyts\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create a in-memory byte stream object
.PP
.SH OPTIONS
.PP
\fBbyts\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
