.\" man page create by R# package system.
.TH FILE 1 2002-May "dir.open" "dir.open"
.SH NAME
dir.open \- Open an interface to a specific local filesystem location
.SH SYNOPSIS
\fIdir.open(\fBdir\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Open an interface to a specific local filesystem location
.PP
.SH OPTIONS
.PP
\fBdir\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
