.\" man page create by R# package system.
.TH FILE 1 2002-May "dir.copy" "dir.copy"
.SH NAME
dir.copy \- copy file contents in one dir to another dir
.SH SYNOPSIS
\fIdir.copy(\fBfrom\fR as string, 
\fBto\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
copy file contents in one dir to another dir
.PP
.SH OPTIONS
.PP
\fBfrom\fB \fR\- -. 
.PP
.PP
\fBto\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
