.\" man page create by R# package system.
.TH FILE 1 2002-May "file.ext" "file.ext"
.SH NAME
file.ext \- Get file extension name
.SH SYNOPSIS
\fIfile.ext(\fBpath\fR as any);\fR
.SH DESCRIPTION
.PP
Get file extension name
.PP
.SH OPTIONS
.PP
\fBpath\fB \fR\- the file path string. 
.PP
.SH VALUE
.PP
returns a file extension suffix name in lower case, if there is 
 no extension name or path string is empty, then empty string 
 value will be returned.
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
