.\" man page create by R# package system.
.TH FILE 1 2002-May "fileSha1" "fileSha1"
.SH NAME
fileSha1 \- Generate SHA1 checksum of a file
.SH SYNOPSIS
\fIfileSha1(\fBfilePath\fR as string);\fR
.SH DESCRIPTION
.PP
Generate SHA1 checksum of a file
.PP
.SH OPTIONS
.PP
\fBfilePath\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
