.\" man page create by R# package system.
.TH FILE 1 2002-May "unlink" "unlink"
.SH NAME
unlink \- Delete files or directories
.SH SYNOPSIS
\fIunlink(\fBx\fR as string);\fR
.SH DESCRIPTION
.PP
Delete files or directories
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function is the alias name of the function
 \fBfile.remove\fR.
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
