.\" man page create by R# package system.
.TH FILE 1 2002-May "writeBin" "writeBin"
.SH NAME
writeBin \- 
.SH SYNOPSIS
\fIwriteBin(\fBobject\fR as any, 
\fBcon\fR as any, 
\fBsize\fR as integer = -2147483648, 
\fBendian\fR as <integer> endianness = [big], 
\fBuseBytes\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fB[object]\fB \fR\- -. 
.PP
.PP
\fBcon\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBendian\fB \fR\- -. 
.PP
.PP
\fBuseBytes\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
file
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
