.\" man page create by R# package system.
.TH IGRAPH.LAYOUTS 4 2020-12-19 "layout.force_directed" "layout.force_directed"
.SH NAME
layout.force_directed \- Do force directed layout
.SH SYNOPSIS
\fIlayout.force_directed(\fBg\fR as <generic> NetworkGraph, 
\fBejectFactor\fR as integer = 6, 
\fBcondenseFactor\fR as integer = 3, 
\fBmaxtx\fR as integer = 4, 
\fBmaxty\fR as integer = 3, 
\fBdist\fR as <generic> Object = "30,250", 
\fBsize\fR as <generic> Object = "1000,1000", 
\fBiterations\fR as integer = 200, 
\fBgroupPlanner\fR as boolean = FALSE, 
\fBgroupAttraction\fR as double = 5, 
\fBgroupRepulsive\fR as double = 5, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do force directed layout
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- A network graph object.
.PP
.PP
\fBiterations\fB \fR\- The number of layout iterations.
.PP
.SH SEE ALSO
igraph.layouts
.SH FILES
.PP
R.graph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
.SH COPYRIGHT
Copyright © SMRUCC 2019
