.\" man page create by R# package system.
.TH SEARCH 1 2002-May "blockIndex" "blockIndex"
.SH NAME
blockIndex \- 
.SH SYNOPSIS
\fIblockIndex(\fBv\fR as <generic> Array, 
\fBtolerance\fR as double, 
\fBeval\fR as <generic> DeclareLambdaFunction, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
search
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
