.\" man page create by R# package system.
.TH LINQ 1 2002-May "groupBy" "groupBy"
.SH NAME
groupBy \- group vector/list by a given evaluator or group a dataframe rows
.SH SYNOPSIS
\fIgroupBy(\fBsequence\fR as any, 
\fBgetKey\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
group vector/list by a given evaluator or group a dataframe rows
 by the cell values of a specific column.
.PP
.SH OPTIONS
.PP
\fBsequence\fB \fR\- -. 
.PP
.PP
\fBgetKey\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
this function could also accept a numeric tolerance error as the
 **`getKey`** for do numeric bin grouping
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
