.\" man page create by R# package system.
.TH LINQ 1 2002-May "left_join" "left_join"
.SH NAME
left_join \- 
.SH SYNOPSIS
\fIleft_join(\fBleft\fR as <generic> dataframe, 
\fBright\fR as <generic> dataframe, 
\fBby_x\fR as string = \fB<NULL>\fR, 
\fBby_y\fR as string = \fB<NULL>\fR, 
\fBby\fR as string = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBleft\fB \fR\- -. 
.PP
.PP
\fBright\fB \fR\- -. 
.PP
.PP
\fBby\fB \fR\- -. 
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
