.\" man page create by R# package system.
.TH LINQ 1 2002-May "rotate_right" "rotate_right"
.SH NAME
rotate_right \- 
.SH SYNOPSIS
\fIrotate_right(\fBx\fR as any, 
\fBi\fR as integer, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
