.\" man page create by R# package system.
.TH LINQ 1 2002-May "unique" "unique"
.SH NAME
unique \- Returns distinct elements from a sequence by using a specified
.SH SYNOPSIS
\fIunique(\fBitems\fR as any, 
\fBgetKey\fR as <generic> RFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Returns distinct elements from a sequence by using a specified 
 IEqualityComparer to compare values.
.PP
.SH OPTIONS
.PP
\fBitems\fB \fR\- The sequence to remove duplicate elements from.. 
.PP
.PP
\fBgetKey\fB \fR\- An IEqualityComparer to compare values.. 
.PP
.PP
\fBenvir\fB \fR\- -. 
.PP
.SH VALUE
.PP
An IEnumerable that contains distinct elements from
 the source sequence.
.PP
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
