.\" man page create by R# package system.
.TH LINQ 1 2002-May "while" "while"
.SH NAME
while \- 
.SH SYNOPSIS
\fIwhile(\fBseq\fR as any, 
\fBpredicate\fR as <generic> RFunction, 
\fBaction\fR as string = "take", 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
linq
.SH FILES
.PP
REnv.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@live.com\fR
.SH COPYRIGHT
GPL3
