<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TestRData</RootNamespace>
    <AssemblyName>TestRData</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <StartupObject>TestRData.Module1</StartupObject>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RData.NET5.vbproj" />
    <ProjectReference Include="..\..\..\R#\Rsharp-netcore5.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="My Project\**" />
    <EmbeddedResource Remove="My Project\**" />
    <None Remove="My Project\**" />
  </ItemGroup>
</Project>
