.TH BINARYTEST 1 2021-04-29 "" "binaryTest"
.SH NAME
binaryTest \- binaryTest(a, b = [a, 1, 5, 666])
.SH SYNOPSIS
\fIbinaryTest(a, b = [a, 1, 5, 666])\fR
.SH OPTIONS
.PP
\fBa\fB \fR\- 
.PP
.PP
\fBb\fB \fR\- [a, 1, 5, 666]
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.binaryTest at bin.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
