.TH DOREQUIRE 1 2021-04-29 "" "doRequire"
.SH NAME
doRequire \- doRequire(pkgName)
.SH SYNOPSIS
\fIdoRequire(pkgName)\fR
.SH OPTIONS
.PP
\fBpkgName\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.doRequire at requireInternal.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
