.TH FUNC 1 2021-04-29 "keyword1,keyword2,keyword3" "test function title"
.SH NAME
func \- func(a, b = [1, 2, 3], c = [12345, FALSE], d = list(a = 1, b = 333))
.SH SYNOPSIS
\fIfunc(a, b = [1, 2, 3], c = [12345, FALSE], d = list(a = 1, b = 333))\fR
.SH DESCRIPTION
.PP
test description with multiple lines
.PP
.SH OPTIONS
.PP
\fBa\fB \fR\- 
.PP
.PP
\fBb\fB \fR\- [1, 2, 3]
.PP
.PP
\fBc\fB \fR\- [12345, FALSE]
.PP
.PP
\fBd\fB \fR\- list(a = 1, b = 333)
.PP
.SH VALUE
.PP
nothing?
.PP
.SH DETAILS
.PP
this is the remark text about this function
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.func at docTest.R:line 19
.PP
.SH AUTHOR
Written by \fBxieguigang\fR
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
