.TH HELLO_WORLD 1 2021-04-29 "" "hello_world"
.SH NAME
hello_world \- hello_world(words = [user, world])
.SH SYNOPSIS
\fIhello_world(words = [user, world])\fR
.SH OPTIONS
.PP
\fBwords\fB \fR\- [user, world]
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.hello_world at hello.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
