.TH IMPORTS_INTERNAL_ASSEMBLY 1 2021-04-29 "" "imports_internal_assembly"
.SH NAME
imports_internal_assembly \- imports_internal_assembly()
.SH SYNOPSIS
\fIimports_internal_assembly()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.imports_internal_assembly at requireInternal.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
