.TH LAMBDA_TEST 1 2021-04-29 "" "lambda_test"
.SH NAME
lambda_test \- lambda_test(dir = !script[[dir]])
.SH SYNOPSIS
\fIlambda_test(dir = !script[[dir]])\fR
.SH OPTIONS
.PP
\fBdir\fB \fR\- !script[[dir]]
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.lambda_test at lorenz.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
