.TH RUNFORMULAFIT 1 2021-04-29 "" "runFormulaFit"
.SH NAME
runFormulaFit \- runFormulaFit(a = [1, 2, 3.2, 4, 5], b = [2, 4, 6, 8, 10])
.SH SYNOPSIS
\fIrunFormulaFit(a = [1, 2, 3.2, 4, 5], b = [2, 4, 6, 8, 10])\fR
.SH OPTIONS
.PP
\fBa\fB \fR\- [1, 2, 3.2, 4, 5]
.PP
.PP
\fBb\fB \fR\- [2, 4, 6, 8, 10]
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.runFormulaFit at lm_formulaTest.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
