.TH SYMBOLTEST_FUNC 1 2021-04-29 "" "symboltest_func"
.SH NAME
symboltest_func \- symboltest_func(a, b)
.SH SYNOPSIS
\fIsymboltest_func(a, b)\fR
.SH OPTIONS
.PP
\fBa\fB \fR\- 
.PP
.PP
\fBb\fB \fR\- 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.symboltest_func at symboltest.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang, bionovogene Licensed 2021
