.\" man page create by R# package system.
.TH RCONVERSION 1 2002-May "as.date" "as.date"
.SH NAME
as.date \- parse string text content as date time values
.SH SYNOPSIS
\fIas.date(\fBobj\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
parse string text content as date time values
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
