.\" man page create by R# package system.
.TH RCONVERSION 1 2002-May "as.numeric" "as.numeric"
.SH NAME
as.numeric \- Numeric Vectors
.SH SYNOPSIS
\fIas.numeric(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Numeric Vectors
 
 Creates or coerces objects of type "numeric". is.numeric is a more 
 general test of an object being interpretable as numbers.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- object to be coerced or tested.. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
\fBNULL\fR will be treated as ZERO based on the rule of VisualBasic 
 runtime conversion, the \fBas.numeric\fR function makes an array value 
 copy always.
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
