.\" man page create by R# package system.
.TH RCONVERSION 1 2002-May "as.raw" "as.raw"
.SH NAME
as.raw \- cast any R# object to raw buffer
.SH SYNOPSIS
\fIas.raw(\fBobj\fR as any, 
\fBencoding\fR as <integer> Encodings = [UTF8WithoutBOM], 
\fBnetworkByteOrder\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
cast any R# object to raw buffer
.PP
.SH OPTIONS
.PP
\fBobj\fB \fR\- numeric values or character vector. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
A stream object that contains raw bytes data
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
