.\" man page create by R# package system.
.TH RCONVERSION 1 2002-May "is.date" "is.date"
.SH NAME
is.date \- the given string is in datetime format?
.SH SYNOPSIS
\fIis.date(\fBstr\fR as string);\fR
.SH DESCRIPTION
.PP
the given string is in datetime format?
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- -. 
.PP
.SH SEE ALSO
RConversion
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
