.\" man page create by R# package system.
.TH MACHINELEARNING 2 2000-Jan "ANN.predict" "ANN.predict"
.SH NAME
ANN.predict \- 
.SH SYNOPSIS
\fIANN.predict(\fBmodel\fR as any, 
\fBinput\fR as double, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
machineLearning
.SH FILES
.PP
MLkit.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gcmodeller.org\fR
.SH COPYRIGHT
I@XIEGUIGANG.ME
