.\" man page create by R# package system.
.TH LAYOUTS 4 2000-Jan "layout.circular_force" "layout.circular_force"
.SH NAME
layout.circular_force \- Do force directed layout
.SH SYNOPSIS
\fIlayout.circular_force(\fBg\fR as <generic> NetworkGraph, 
\fBejectFactor\fR as integer = 6, 
\fBcondenseFactor\fR as integer = 3, 
\fBmaxtx\fR as integer = 4, 
\fBmaxty\fR as integer = 3, 
\fBdist\fR as any = "30,250", 
\fBsize\fR as any = "1000,1000", 
\fBiterations\fR as integer = 200, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do force directed layout
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- A network graph object.. 
.PP
.PP
\fBiterations\fB \fR\- The number of layout iterations.. 
.PP
.SH SEE ALSO
layouts
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
