.\" man page create by R# package system.
.TH LAYOUTS 4 2000-Jan "layout.random" "layout.random"
.SH NAME
layout.random \- do random layout of the given network graph object and then returns the given graph object.
.SH SYNOPSIS
\fIlayout.random(\fBg\fR as <generic> NetworkGraph, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do random layout of the given network graph object and then returns the given graph object.
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
layouts
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
