.\" man page create by R# package system.
.TH LAYOUTS 4 2000-Jan "layout.orthogonal" "layout.orthogonal"
.SH NAME
layout.orthogonal \- do orthogonal layout for the network graph input
.SH SYNOPSIS
\fIlayout.orthogonal(\fBg\fR as <generic> NetworkGraph, 
\fBgridSize\fR as any = "1000,1000", 
\fBdelta\fR as double = 13, 
\fBlayoutIteration\fR as integer = -1, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
do orthogonal layout for the network graph input
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- -. 
.PP
.PP
\fBgridSize\fB \fR\- -. 
.PP
.PP
\fBdelta\fB \fR\- the node movement delta. 
.PP
.PP
\fBlayoutIteration\fB \fR\- 
 the iteration number for run the layout process, \fB-1\fR means auto calculation.
. 
.PP
.SH SEE ALSO
layouts
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
