.\" man page create by R# package system.
.TH LAYOUTS 4 2000-Jan "layout.springForce" "layout.springForce"
.SH NAME
layout.springForce \- Do force directed layout
.SH SYNOPSIS
\fIlayout.springForce(\fBg\fR as <generic> NetworkGraph, 
\fBstiffness\fR as double = 80, 
\fBrepulsion\fR as double = 4000, 
\fBdamping\fR as double = 0.83, 
\fBiterations\fR as integer = 1000, 
\fBclearScreen\fR as boolean = FALSE, 
\fBshowProgress\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Do force directed layout
.PP
.SH OPTIONS
.PP
\fBg\fB \fR\- A network graph object.. 
.PP
.PP
\fBiterations\fB \fR\- The number of layout iterations.. 
.PP
.PP
\fBclearScreen\fB \fR\- 
 Clear of the console screen when display the progress bar.
. 
.PP
.SH SEE ALSO
layouts
.SH FILES
.PP
igraph.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
