.\" man page create by R# package system.
.TH RANKING 1 2002-May "rank" "rank"
.SH NAME
rank \- Sample Ranks
.SH SYNOPSIS
\fIrank(\fBx\fR as double, 
\fBna_last\fR as boolean = TRUE, 
\fBties_method\fR as <integer> Strategies = [OrdinalRanking]);\fR
.SH DESCRIPTION
.PP
Sample Ranks
 
 Returns the sample ranks of the values in a vector. Ties 
 (i.e., equal values) and missing values can be handled in
 several ways.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a numeric, complex, character Or logical vector.. 
.PP
.PP
\fBna_last\fB \fR\- 	
 For controlling the treatment of NAs. If TRUE, missing values in the 
 data are put last; if FALSE, they are put first; if NA, they are 
 removed; if "keep" they are kept with rank NA.. 
.PP
.PP
\fBties_method\fB \fR\- 
 a character string specifying how ties are treated, see ‘Details’; 
 can be abbreviated.
. 
.PP
.SH VALUE
.PP
A numeric vector of the same length as x with names copied from x 
 (unless na.last = NA, when missing values are removed). The vector is 
 of integer type unless x is a long vector or ties.method = "average" when 
 it is of double type (whether or not there are any ties).
.PP
.SH DETAILS
.PP
If all components are different (and no NAs), the ranks are well defined, 
 with values in seq_along(x). With some values equal (called ‘ties’), 
 the argument ties.method determines the result at the corresponding indices. 
 The "first" method results in a permutation with increasing values at each 
 index set of ties, and analogously "last" with decreasing values. The 
 "random" method puts these in random order whereas the default, "average", 
 replaces them by their mean, and "max" and "min" replaces them by their 
 maximum and minimum respectively, the latter being the typical sports 
 ranking.

 NA values are never considered to be equal: for na.last = TRUE and \fBna.last = FALSE\fR
 they are given distinct ranks in the order in which they occur in x.

 NB: rank is not itself generic but xtfrm is, and rank(xtfrm(x), ....) will have 
 the desired result if there is a xtfrm method. Otherwise, rank will make use 
 of ==, >, is.na and extraction methods for classed objects, possibly rather 
 slowly.
.PP
.SH SEE ALSO
ranking
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
