.\" man page create by R# package system.
.TH MATH 1 2002-May "diff" "diff"
.SH NAME
diff \- Lagged Differences
.SH SYNOPSIS
\fIdiff(\fBx\fR as double);\fR
.SH DESCRIPTION
.PP
Lagged Differences
 
 Returns suitably lagged and iterated differences.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 a numeric vector Or matrix containing the values To be differenced.
. 
.PP
.SH DETAILS
.PP
is.finite returns a vector of the same length as x the jth 
 element of which is TRUE if x[j] is finite (i.e., it is not 
 one of the values NA, NaN, Inf or -Inf) and FALSE otherwise. 
 Complex numbers are finite if both the real and imaginary 
 parts are.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
