.\" man page create by R# package system.
.TH MATH 1 2002-May "log10" "log10"
.SH NAME
log10 \- Logarithms and Exponentials
.SH SYNOPSIS
\fIlog10(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Logarithms and Exponentials
 
 log10 computes common (i.e., base 10) logarithms
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
