.\" man page create by R# package system.
.TH MATH 1 2002-May "log2" "log2"
.SH NAME
log2 \- Logarithms and Exponentials
.SH SYNOPSIS
\fIlog2(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
Logarithms and Exponentials
 
 log2 computes binary (i.e., base 2) logarithms.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
