.\" man page create by R# package system.
.TH MATH 1 2002-May "min" "min"
.SH NAME
min \- 
.SH SYNOPSIS
\fImin(\fBx\fR as any, 
\fBna_rm\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBna_rm\fB \fR\- 
 a logical indicating whether missing values should be removed.
. 
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
