.\" man page create by R# package system.
.TH MATH 1 2002-May "rsd" "rsd"
.SH NAME
rsd \- relative standard deviation
.SH SYNOPSIS
\fIrsd(\fBx\fR as any);\fR
.SH DESCRIPTION
.PP
relative standard deviation
 
 Relative standard deviation is a common formula 
 used in statistics and probability theory to determine
 a standardized measure of the ratio of the standard
 deviation to the mean. This formula is useful in
 various situations including when comparing your 
 own data to other related data and in financial 
 settings such as the stock market.
 
 Relative standard deviation, which also may be referred 
 to as RSD or the coefficient of variation, is used 
 to determine if the standard deviation of a set of 
 data is small or large when compared to the mean.
 In other words, the relative standard deviation can
 tell you how precise the average of your results is.
 This formula is most frequently used in chemistry, 
 statistics and other math-related settings but can 
 also be used in the business world when assessing
 finances and the stock market.
 
 The relative standard deviation Of a Set Of data can be
 depicted As either a percentage Or As a number. The 
 higher the relative standard deviation, the more spread 
 out the results are from the mean Of the data. On the
 other hand, a lower relative standard deviation means 
 that the measurement Of data Is more precise.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
