.\" man page create by R# package system.
.TH MATH 1 2002-May "sample.int" "sample.int"
.SH NAME
sample.int \- 
.SH SYNOPSIS
\fIsample.int(\fBn\fR as integer, 
\fBsize\fR as any = "n", 
\fBreplace\fR as boolean = FALSE, 
\fBprob\fR as any = \fB<NULL>\fR);\fR
.SH OPTIONS
.PP
\fBn\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBreplace\fB \fR\- -. 
.PP
.PP
\fBprob\fB \fR\- -. 
.PP
.SH VALUE
.PP
returns an integer vector that could be used for represents the element index
 the generated integer vector in this function is base from 1
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
