.\" man page create by R# package system.
.TH MATH 1 2002-May "sign" "sign"
.SH NAME
sign \- Sign Function
.SH SYNOPSIS
\fIsign(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Sign Function
 
 sign returns a vector with the signs of the corresponding 
 elements of x (the sign of a real number is 1, 0, or -1−1 
 if the number is positive, zero, or negative, respectively).
 
 Note that sign does not operate on complex vectors.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- a numeric vector. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
This is an internal generic primitive function: methods can 
 be defined for it directly or via the Math group generic.
.PP
.SH SEE ALSO
math
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
