.\" man page create by R# package system.
.TH MATH 1 2000-Jan "zero" "zero"
.SH NAME
zero \- Get the additive identity element for the type of x (x can also specify the type itself).
.SH SYNOPSIS
\fIzero(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get the additive identity element for the type of x (x can also specify the type itself).
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.SH SEE ALSO
math
.SH FILES
.PP
njl.dll
.PP
