.TH __CODESCRIPT 1 2024-Jul "" "__codescript"
.SH NAME
__codescript \- __codescript(code)
.SH SYNOPSIS
\fI__codescript(code)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__codescript at rlang.R:line 20
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
