.TH __RSYMBOLDOCUMENTATION 1 2024-Jan "" "__RSymbolDocumentation"
.SH NAME
__RSymbolDocumentation \- __RSymbolDocumentation(symbols, package,
    <i>outputdir</i> = ./)
.SH SYNOPSIS
\fI__RSymbolDocumentation(symbols, package,
    <i>outputdir</i> = ./)\fR
.SH OPTIONS
.PP
\fBsymbols\fB \fR\- . 
.PP
.PP
\fBpackage\fB \fR\- . 
.PP
.PP
\fBoutputdir\fB \fR\- ./. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__RSymbolDocumentation at rdocumentation.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
