.TH __SOURCESCRIPT 1 2024-Sep "" "An internal helper function for attach the dependency scripts"
.SH NAME
__sourcescript \- __sourcescript(source)
.SH SYNOPSIS
\fI__sourcescript(source)\fR
.SH OPTIONS
.PP
\fBsource\fB \fR\- . a collection of the source scripts filepath for load inside the context.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__sourcescript at dependecy.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
