.TH __SOURCESCRIPT 1 2024-Jul "" "__sourcescript"
.SH NAME
__sourcescript \- __sourcescript(source)
.SH SYNOPSIS
\fI__sourcescript(source)\fR
.SH OPTIONS
.PP
\fBsource\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__sourcescript at rlang.R:line 45
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
