.TH __TEMPLATE 1 2025-Aug "" "An internal helper function for try to get the html document template"
.SH NAME
__template \- __template()
.SH SYNOPSIS
\fI__template()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.__template at template.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
