.TH __TEMPLATE 1 2025-Oct "" "An internal helper function for try to get the html document template"
.SH NAME
__template \- __template()
.SH SYNOPSIS
\fI__template()\fR
.SH VALUE
.PP
a tuple list that contains two template elements:
+ template: the html document template for the R# runtime symbols which is defined inside the R source script files.
+ clr_template: the html document template for the clr object which is exported from the .NET dll assembly files.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.__template at template.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
