.TH CLASSIFY_CANCER 1 2022-08-03 "" "http://www.sph.emory.edu/~dkleinb/datasets/cancer.dat"
.SH NAME
classify_cancer \- classify_cancer()
.SH SYNOPSIS
\fIclassify_cancer()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.classify_cancer at datasets.R:line 4
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
