.TH CODE_STATS 1 2024-May "" "export the result as csv file"
.SH NAME
code_stats \- code_stats(stats, proj.folder, save)
.SH SYNOPSIS
\fIcode_stats(stats, proj.folder, save)\fR
.SH OPTIONS
.PP
\fBstats\fB \fR\- . 
.PP
.PP
\fBproj.folder\fB \fR\- . 
.PP
.PP
\fBsave\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.code_stats at vbcode_banner.R:line 106
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
