.TH COERCE_DATAFRAME 1 2024-Jul "" "coerce_dataframe"
.SH NAME
coerce_dataframe \- coerce_dataframe(x)
.SH SYNOPSIS
\fIcoerce_dataframe(x)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.coerce_dataframe at datasets.R:line 39
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
