.TH DENSITY2DCUT 1 2024-May "" "Evaluate geom density of 2d points"
.SH NAME
density2DCut \- density2DCut(data,
    <i>k</i> = <span style='color: green;'>6</span>,
    <i>qcut</i> = <span style='color: green;'>0.1</span>,
    <i>f</i> = <span style='color: green;'>10</span>)
.SH SYNOPSIS
\fIdensity2DCut(data,
    <i>k</i> = <span style='color: green;'>6</span>,
    <i>qcut</i> = <span style='color: green;'>0.1</span>,
    <i>f</i> = <span style='color: green;'>10</span>)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBk\fB \fR\- 6. 
.PP
.PP
\fBqcut\fB \fR\- 0.1. the quantile cutoff threshold for define points as low density points(noise).
.PP
.PP
\fBf\fB \fR\- 10. 
.PP
.SH VALUE
.PP
a new dataframe object with data fields: x, y, density, and noise boolean flags
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.density2DCut at geom.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
