.TH DENSITY2DCUT 1 2022-01-10 "" "Evaluate geom density of 2d points"
.SH NAME
density2DCut \- density2DCut(data, k = 6, qcut = 0.1, f = 10)
.SH SYNOPSIS
\fIdensity2DCut(data, k = 6, qcut = 0.1, f = 10)\fR
.SH OPTIONS
.PP
\fBdata\fB \fR\- . 
.PP
.PP
\fBk\fB \fR\- 6. 
.PP
.PP
\fBqcut\fB \fR\- 0.1. the quantile cutoff threshold for define points as low density points(noise).
.PP
.PP
\fBf\fB \fR\- 10. 
.PP
.SH VALUE
.PP
a new dataframe object with data fields: x, y, density, and noise boolean flags
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.<$anonymous_0379a> at geom.R:line 11
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
