.TH GETHTML 1 2022-07-13 "" "Http get html or from cache"
.SH NAME
getHtml \- getHtml(url, interval = 3, filetype = html)
.SH SYNOPSIS
\fIgetHtml(url, interval = 3, filetype = html)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the url of the resource data on the remote server
.PP
.PP
\fBinterval\fB \fR\- 3. the time interval in seconds for sleep after request data from the remote server.
.PP
.PP
\fBfiletype\fB \fR\- html. 
.PP
.SH DETAILS
.PP
using of the http get function required of set options of ``http.cache_dir`` at first!
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.getHtml at http.R:line 90
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
