.TH INCLUDE 1 2025-Sep "" "include"
.SH NAME
include \- include(file)
.SH SYNOPSIS
\fIinclude(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.include at include.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
