.TH INCLUDE_JSONCONFIG 1 2025-Jul "" "include_jsonconfig"
.SH NAME
include_jsonconfig \- include_jsonconfig(file)
.SH SYNOPSIS
\fIinclude_jsonconfig(file)\fR
.SH OPTIONS
.PP
\fBfile\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.include_jsonconfig at include.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
