.TH NATIVE_R 1 2026-Feb "" "make native r function call"
.SH NAME
native_r \- native_r(f,
    <i>args</i> = 'list'(),
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>deps</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>native.R</i> = 'getOption'('native_rexec'))
.SH SYNOPSIS
\fInative_r(f,
    <i>args</i> = 'list'(),
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>deps</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>native.R</i> = 'getOption'('native_rexec'))\fR
.SH OPTIONS
.PP
\fBf\fB \fR\- . target r function code to be run in native r environment
.PP
.PP
\fBargs\fB \fR\- 'list'(). the function invoke parameters
.PP
.PP
\fBworkdir\fB \fR\- NULL. the workdir of the sub-process of the native R
.PP
.PP
\fBdeps\fB \fR\- NULL. 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.PP
\fBnative.R\fB \fR\- 'getOption'('native_rexec'). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.native_r at native_r.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2026
