.TH PALETTEER_COLORS 1 2025-Oct "" "paletteer_colors"
.SH NAME
paletteer_colors \- paletteer_colors(palette)
.SH SYNOPSIS
\fIpaletteer_colors(palette)\fR
.SH OPTIONS
.PP
\fBpalette\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.paletteer_colors at paletteer.R:line 30
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
