.TH PLATFORMNAME 1 2024-May "" "get system os name"
.SH NAME
platformName \- platformName()
.SH SYNOPSIS
\fIplatformName()\fR
.SH VALUE
.PP
"Windows" for Microsoft Windows
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.platformName at utils.R:line 24
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
