.TH PLATFORMNAME 1 2022-04-24 "" "get system os name"
.SH NAME
platformName \- platformName()
.SH SYNOPSIS
\fIplatformName()\fR
.SH VALUE
.PP
"Windows" for Microsoft Windows
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.platformName at utils.R:line 24
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
