.TH PROCESS_PROJECT 1 2024-May "" "process_project"
.SH NAME
process_project \- process_project(vbproj, refer, banner, proj.folder,
    <i>stat</i> = 'list'('totalLines' = [], 'commentLines' = [], 'blankLines' = [], 'size' = [], 'lineOfCodes' = [], 'classes' = [], 'method' = [], 'operator' = [], 'functions' = [], 'property' = [], 'files' = [], 'projList' = []))
.SH SYNOPSIS
\fIprocess_project(vbproj, refer, banner, proj.folder,
    <i>stat</i> = 'list'('totalLines' = [], 'commentLines' = [], 'blankLines' = [], 'size' = [], 'lineOfCodes' = [], 'classes' = [], 'method' = [], 'operator' = [], 'functions' = [], 'property' = [], 'files' = [], 'projList' = []))\fR
.SH OPTIONS
.PP
\fBvbproj\fB \fR\- . 
.PP
.PP
\fBrefer\fB \fR\- . 
.PP
.PP
\fBbanner\fB \fR\- . 
.PP
.PP
\fBproj.folder\fB \fR\- . 
.PP
.PP
\fBstat\fB \fR\- 'list'('totalLines' = [], 'commentLines' = [], 'blankLines' = [], 'size' = [], 'lineOfCodes' = [], 'classes' = [], 'method' = [], 'operator' = [], 'functions' = [], 'property' = [], 'files' = [], 'projList' = []). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.process_project at vbcode_banner.R:line 31
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
