.TH PROCESSSINGLE 1 2024-May "" "processSingle"
.SH NAME
processSingle \- processSingle(refer, banner, proj.folder,
    <i>stat</i> = 'list'())
.SH SYNOPSIS
\fIprocessSingle(refer, banner, proj.folder,
    <i>stat</i> = 'list'())\fR
.SH OPTIONS
.PP
\fBrefer\fB \fR\- . 
.PP
.PP
\fBbanner\fB \fR\- . 
.PP
.PP
\fBproj.folder\fB \fR\- . 
.PP
.PP
\fBstat\fB \fR\- 'list'(). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.processSingle at vbcode_banner.R:line 71
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
