.TH QUERYWEB 1 2022-08-20 "" "Run graphquery on html document"
.SH NAME
queryWeb \- queryWeb(url, graphquery)
.SH SYNOPSIS
\fIqueryWeb(url, graphquery)\fR
.SH OPTIONS
.PP
\fBurl\fB \fR\- . the url or local filepath of the target html document
.PP
.PP
\fBgraphquery\fB \fR\- . the script text of a required given graphquery
.PP
.SH VALUE
.PP
A ``R#`` object that parsed from the target html web page with given query expression value.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.queryWeb at utils.R:line 13
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
