.TH RDOCUMENTS 1 2022-12-12 "" "Create html documents for ``R#`` package module"
.SH NAME
Rdocuments \- Rdocuments(pkgName,
    <i>outputdir</i> = ./)
.SH SYNOPSIS
\fIRdocuments(pkgName,
    <i>outputdir</i> = ./)\fR
.SH OPTIONS
.PP
\fBpkgName\fB \fR\- . the ``R#`` package module itself or the package character text name.
.PP
.PP
\fBoutputdir\fB \fR\- ./. the output directory path for save the html documents.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.Rdocuments at utils.R:line 44
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2022
