.TH RDOCUMENTS 1 2023-Dec "" "Create html documents for ``R#`` package module"
.SH NAME
Rdocuments \- Rdocuments(pkgName,
    <i>outputdir</i> = ./,
    <i>package</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIRdocuments(pkgName,
    <i>outputdir</i> = ./,
    <i>package</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBpkgName\fB \fR\- . the ``R#`` package module itself or the package character text name.
.PP
.PP
\fBoutputdir\fB \fR\- ./. the output directory path for save the html documents.
.PP
.PP
\fBpackage\fB \fR\- NULL. a character vector for display the package name
.PP
.SH DETAILS
.PP
the parameter pkgName is different with package parameter, for 1. package parameter is standard for the R# zip package its namespace 2. pkgName parameter usually be one of a clr dll module
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.Rdocuments at rdocumentation.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
