.TH RDOCUMENTS 1 2023-6月 "" "Create html documents for ``R#`` package module"
.SH NAME
Rdocuments \- Rdocuments(pkgName,
    <i>outputdir</i> = ./,
    <i>package</i> = <span style='color: blue;'>NULL</span>)
.SH SYNOPSIS
\fIRdocuments(pkgName,
    <i>outputdir</i> = ./,
    <i>package</i> = <span style='color: blue;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBpkgName\fB \fR\- . the ``R#`` package module itself or the package character text name.
.PP
.PP
\fBoutputdir\fB \fR\- ./. the output directory path for save the html documents.
.PP
.PP
\fBpackage\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.Rdocuments at utils.R:line 44
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
