.TH RLANG_INTEROP 1 2024-Nov "" "helper function for R# interop with R language"
.SH NAME
rlang_interop \- rlang_interop(code,
    <i>source</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIrlang_interop(code,
    <i>source</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . a closure expresion for invoke R function
.PP
.PP
\fBsource\fB \fR\- NULL. the source file paths for provides the runtime environment for the specific input code.
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.PP
\fBworkdir\fB \fR\- NULL. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.rlang_interop at rlang.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
