.TH RLANG_CALL 1 2026-Feb "" "Execute native R script from current R# process"
.SH NAME
rlang_call \- rlang_call(script.code,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>native.R</i> = 'getOption'('native_rexec'),
    <i>title</i> = <span style='color: blue !important;'>NULL</span>)
.SH SYNOPSIS
\fIrlang_call(script.code,
    <i>workdir</i> = <span style='color: blue !important;'>NULL</span>,
    <i>native.R</i> = 'getOption'('native_rexec'),
    <i>title</i> = <span style='color: blue !important;'>NULL</span>)\fR
.SH DESCRIPTION
.PP


This function executes a native R script file using the system's Rscript executable.
.PP
.SH OPTIONS
.PP
\fBscript.code\fB \fR\- . 
.PP
.PP
\fBworkdir\fB \fR\- NULL. Working directory for executing the R script (default: current directory).
.PP
.PP
\fBnative.R\fB \fR\- 'getOption'('native_rexec'). 
.PP
.PP
\fBtitle\fB \fR\- NULL. 
.PP
.SH VALUE
.PP
This function returns nothing explicitly, but executes the R script and
may produce output, side effects, or results based on the script's contents.
.PP
.SH DETAILS
.PP
The function automatically detects the operating system and uses the
appropriate Rscript executable path for Windows or Linux systems.
It temporarily changes the working directory if specified, then restores
the original directory after execution.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.rlang_call at rlang_call.R:line 17
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2026
