.TH SCALE0_1 1 2023-01-07 "" "Scale values to 0-1 range relative to each other."
.SH NAME
scale0_1 \- scale0_1(x)
.SH SYNOPSIS
\fIscale0_1(x)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . vector or matrix
.PP
.SH VALUE
.PP
vector or matrix with all values adjusted 0-1 scale relative to each other.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.scale0_1 at math.R:line 7
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
