.TH TRANSFORM_RLANG_SOURCE 1 2025-May "" "translate R# code to Rscript text"
.SH NAME
transform_rlang_source \- transform_rlang_source(code,
    <i>source</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fItransform_rlang_source(code,
    <i>source</i> = <span style='color: blue !important;'>NULL</span>,
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBcode\fB \fR\- . 
.PP
.PP
\fBsource\fB \fR\- NULL. 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH VALUE
.PP
this function build rscript text from a given R# closure code
.PP
.SH DETAILS
.PP
this function could be used for generates script for run in docker container
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.transform_rlang_source at rlang.R:line 6
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2025
