.TH WALKFILES 1 2024-Apr "" "process a single vb.net source file"
.SH NAME
walkFiles \- walkFiles(vbproj, refer, banner, proj.folder)
.SH SYNOPSIS
\fIwalkFiles(vbproj, refer, banner, proj.folder)\fR
.SH OPTIONS
.PP
\fBvbproj\fB \fR\- . 
.PP
.PP
\fBrefer\fB \fR\- . 
.PP
.PP
\fBbanner\fB \fR\- . 
.PP
.PP
\fBproj.folder\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.walkFiles at vbcode_banner.R:line 3
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT Licensed 2024
