.\" man page create by R# package system.
.TH HIDDENMARKOV 1 2000-Jan "as.statesMatrix" "as.statesMatrix"
.SH NAME
as.statesMatrix \- 
.SH SYNOPSIS
\fIas.statesMatrix(\fBmatrix\fR as any, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBmatrix\fB \fR\- 
 A dataframe matrix object should contains fields:
 
 \fBstates\fR and probability
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
hiddenMarkov
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
