.\" man page create by R# package system.
.TH HIDDENMARKOV 1 2000-Jan "bayesTheorem" "bayesTheorem"
.SH NAME
bayesTheorem \- 
.SH SYNOPSIS
\fIbayesTheorem(\fBhmm\fR as <generic> HMM, 
\fBobservation\fR as string, 
\fBhiddenState\fR as string);\fR
.SH SEE ALSO
hiddenMarkov
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
