.\" man page create by R# package system.
.TH HIDDENMARKOV 1 2000-Jan "forwardAlgorithm" "forwardAlgorithm"
.SH NAME
forwardAlgorithm \- 
.SH SYNOPSIS
\fIforwardAlgorithm(\fBhmm\fR as <generic> HMM, 
\fBobs\fR as any);\fR
.SH SEE ALSO
hiddenMarkov
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
