.\" man page create by R# package system.
.TH HIDDENMARKOV 1 2000-Jan "sequenceProb" "sequenceProb"
.SH NAME
sequenceProb \- 
.SH SYNOPSIS
\fIsequenceProb(\fBmarkovChain\fR as <generic> MarkovChain, 
\fBseq\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
hiddenMarkov
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
