.\" man page create by R# package system.
.TH SVM 1 2000-Jan "problem.trim" "problem.trim"
.SH NAME
problem.trim \- removes all columns that will all value equals to each other
.SH SYNOPSIS
\fIproblem.trim(\fBmodel\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
removes all columns that will all value equals to each other
.PP
.SH OPTIONS
.PP
\fBmodel\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
SVM
.SH FILES
.PP
MLkit.dll
.PP
.SH COPYRIGHT
I@XIEGUIGANG.ME
