.\" man page create by R# package system.
.TH GEOMETRY2D 1 2000-Jan "concaveHull" "concaveHull"
.SH NAME
concaveHull \- 
.SH SYNOPSIS
\fIconcaveHull(\fBpts\fR as any, 
\fBas_polygon\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH OPTIONS
.PP
\fBpts\fB \fR\- 
 + for dataframe object, data fields x and y should be exists
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
A set of point data which could be used for build a polygon object
.PP
.SH SEE ALSO
geometry2D
.SH FILES
.PP
graphics.dll
.PP
