.\" man page create by R# package system.
.TH GEOMETRY2D 1 2000-Jan "density2D" "density2D"
.SH NAME
density2D \- Evaluate the density value of a set of 2d points.
.SH SYNOPSIS
\fIdensity2D(\fBx\fR as integer, 
\fBy\fR as integer, 
\fBk\fR as integer = 6, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Evaluate the density value of a set of 2d points.
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- -. 
.PP
.PP
\fBy\fB \fR\- -. 
.PP
.PP
\fBk\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
a density value vector. the elements in the resulted density 
 value vector is keeps the same order as the input [x,y] 
 vector.
.PP
.SH SEE ALSO
geometry2D
.SH FILES
.PP
graphics.dll
.PP
