.\" man page create by R# package system.
.TH GEOMETRY2D 1 2000-Jan "Kdtest" "Kdtest"
.SH NAME
Kdtest \- just used for do kd-tree unit test
.SH SYNOPSIS
\fIKdtest(\fBn\fR as integer = 1000, 
\fBknn\fR as integer = 60, 
\fBsize\fR as any = "5200,4500", 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
just used for do kd-tree unit test
.PP
.SH SEE ALSO
geometry2D
.SH FILES
.PP
graphics.dll
.PP
