.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2000-Jan "betweenness_centrality" "betweenness_centrality"
.SH NAME
betweenness_centrality \- 
.SH SYNOPSIS
\fIbetweenness_centrality(\fBg\fR as any, 
\fBundirect\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
igraph.dll
.PP
