.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2000-Jan "router.dijkstra" "router.dijkstra"
.SH NAME
router.dijkstra \- 
.SH SYNOPSIS
\fIrouter.dijkstra(\fBg\fR as <generic> NetworkGraph, 
\fBundirected\fR as boolean = FALSE);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
igraph.dll
.PP
