.\" man page create by R# package system.
.TH IGRAPH.DIJKSTRA 1 2000-Jan "routine.min_cost" "routine.min_cost"
.SH NAME
routine.min_cost \- 
.SH SYNOPSIS
\fIroutine.min_cost(\fBrouter\fR as <generic> DijkstraRouter, 
\fBfrom\fR as any, 
\fBto\fR as any, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
igraph.dijkstra
.SH FILES
.PP
igraph.dll
.PP
