.\" man page create by R# package system.
.TH UTILS 1 2002-May "commandline" "commandline"
.SH NAME
commandline \- create commandline string
.SH SYNOPSIS
\fIcommandline(..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
create commandline string
.PP
.SH OPTIONS
.PP
\fBargv\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
