.\" man page create by R# package system.
.TH UTILS 1 2002-May "md5" "md5"
.SH NAME
md5 \- Vectorized hash/hmac functions
.SH SYNOPSIS
\fImd5(\fBx\fR as any, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Vectorized hash/hmac functions
.PP
.SH OPTIONS
.PP
\fBx\fB \fR\- 
 character vector, raw vector or connection object.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH DETAILS
.PP
Digest types: https://www.openssl.org/docs/man1.1.1/man1/openssl-dgst.html
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
