.\" man page create by R# package system.
.TH UTILS 1 2002-May "package.skeleton" "package.skeleton"
.SH NAME
package.skeleton \- Create a Skeleton for a New Source Package
.SH SYNOPSIS
\fIpackage.skeleton(\fBname\fR as string = "anRpackage", 
\fBpath\fR as string = "./", 
\fBforce\fR as boolean = FALSE, 
\fBcode_files\fR as string = \fB<NULL>\fR, 
\fBencoding\fR as string = "unknown", 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a Skeleton for a New Source Package
 
 package.skeleton automates some of the setup for a new source 
 package. It creates directories, saves functions, data, and 
 R code files to appropriate places, and creates skeleton help
 files and a ‘Read-and-delete-me’ file describing further steps 
 in packaging.
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- 
 character string: the package name and directory name for your package. 
 Must be a valid package name.
. 
.PP
.PP
\fBpath\fB \fR\- path to put the package directory in.. 
.PP
.PP
\fBforce\fB \fR\- 
 If False will Not overwrite an existing directory.. 
.PP
.PP
\fBcode_files\fB \fR\- 
 a character vector with the paths to R code files to build the 
 package around. See ‘Details’.
. 
.PP
.PP
\fBencoding\fB \fR\- 
 optionally a character string with an encoding for an optional 
 Encoding: line in ‘DESCRIPTION’ when non-ASCII characters will 
 be used; typically one of "latin1", "latin2", or "UTF-8"; see 
 the WRE manual.
. 
.PP
.PP
\fBlist\fB \fR\- 
 character vector naming the R objects to put in the package. Usually, 
 at most one of list, environment, or code_files will be supplied. 
 See ‘Details’.
. 
.PP
.PP
\fBenvironment\fB \fR\- 
 an environment where objects are looked for. See ‘Details’.
. 
.PP
.SH VALUE
.PP
Used for its side-effects.
.PP
.SH DETAILS
.PP
The arguments list, environment, and code_files provide alternative
 ways to initialize the package. If code_files is supplied, the files
 so named will be sourced to form the environment, then used to 
 generate the package skeleton. Otherwise list defaults to the objects
 in environment (including those whose names start with .), but can 
 be supplied to select a subset of the objects in that environment.
 
 Stubs of help files are generated for functions, data objects, And S4 
 classes And methods, using the prompt, promptClass, And promptMethods 
 functions. If an object from another package Is intended to be imported 
 And re-exported without changes, the promptImport function should be 
 used after package.skeleton to generate a simple help file linking to 
 the original one.
 
 The package sources are placed In subdirectory name Of path. If code_files 
 Is supplied, these files are copied; otherwise, objects will be dumped 
 into individual source files. The file names In code_files should have 
 suffix ".R" And be In the current working directory.
 
 The filenames created For source And documentation Try To be valid For
 all OSes known To run R. Invalid characters are replaced by _, invalid 
 names are preceded by zz, names are converted To lower Case (To avoid 
 Case collisions On Case-insensitive file systems) And Finally the converted 
 names are made unique by make.unique(sep = "_"). This can be done For 
 code And help files but Not data files (which are looked For by name). 
 Also, the code And help files should have names starting With an ASCII 
 letter Or digit, And this Is checked And If necessary z prepended.
 Functions with names starting with a dot are placed in file 'R/name-internal.R’.
 When you are done, delete the 'Read-and-delete-me’ file, as it should 
 not be distributed.
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
