.\" man page create by R# package system.
.TH UTILS 1 2002-May "wget" "wget"
.SH NAME
wget \- retrieving files using HTTP, HTTPS, FTP and FTPS, the most widely used Internet protocols.
.SH SYNOPSIS
\fIwget(\fBurl\fR as string, 
\fBsave\fR as any = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
retrieving files using HTTP, HTTPS, FTP and FTPS, the most widely used Internet protocols.
.PP
.SH OPTIONS
.PP
\fBurl\fB \fR\- -. 
.PP
.PP
\fBsave\fB \fR\- 
 this parameter could be a character vector for specific a local file path to save the 
 target remote file, or it also could be a file reference wrapper object for store in 
 a cache pack. This function will returns a stream object if this parameter is nothing.
. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH VALUE
.PP
this function will returns the data stream which is download from the given 
 **`url`** if the **`save`** parameter value is 
 nothing by default, or this function will returns nothing if the **`save`** 
 parameter value is exists and also the http resource data will be placed at 
 **`save`** file location.
.PP
.SH SEE ALSO
utils
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
