.\" man page create by R# package system.
.TH CHARTS 4 2000-Jan "contourPlot" "contourPlot"
.SH NAME
contourPlot \- A contour plot is a graphical technique for representing a 3-dimensional
.SH SYNOPSIS
\fIcontourPlot(\fBdata\fR as any, 
\fBcolorSet\fR as any = "Spectral:c10", 
\fBxlim\fR as double = NAN, 
\fBylim\fR as double = NAN, 
..., 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
A contour plot is a graphical technique for representing a 3-dimensional 
 surface by plotting constant z slices, called contours, on a 2-dimensional 
 format. That is, given a value for z, lines are drawn for connecting the 
 \fB(x,y)\fR coordinates where that z value occurs.
 
 The contour plot Is an alternative To a 3-D surface plot.
.PP
.SH OPTIONS
.PP
\fBdata\fB \fR\- -. 
.PP
.PP
\fBargs\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
charts
.SH FILES
.PP
graphics.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
