.\" man page create by R# package system.
.TH CHARTS 4 2000-Jan "fillPolygon" "fillPolygon"
.SH NAME
fillPolygon \- 
.SH SYNOPSIS
\fIfillPolygon(\fBpolygon\fR as any, 
\fBpadding\fR as any = "padding:250px 150px 300px 300px;", 
\fBgrid_fill\fR as any = "white", 
\fBreverse\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
charts
.SH FILES
.PP
graphics.dll
.PP
.SH AUTHOR
Written by \fBxie.guigang@gmail.com\fR
