.\" man page create by R# package system.
.TH ENV 1 2002-May "environment" "environment"
.SH NAME
environment \- Get current environment or envirnment of target function closure
.SH SYNOPSIS
\fIenvironment(\fBfun\fR as <closure> DeclareNewFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Get current environment or envirnment of target function closure
.PP
.SH OPTIONS
.PP
\fBenv\fB \fR\- -. 
.PP
.PP
\fBfun\fB \fR\- 
 a Function, a formula, Or NULL, which Is the default.
. 
.PP
.SH VALUE
.PP
If fun is a function or a formula then environment(fun) returns 
 the environment associated with that function or formula. If fun 
 is NULL then the current evaluation environment is returned.
.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
