.\" man page create by R# package system.
.TH ENV 1 2002-May "type" "type"
.SH NAME
type \- get exported type by name
.SH SYNOPSIS
\fItype(\fBname\fR as string, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
get exported type by name
.PP
.SH OPTIONS
.PP
\fBname\fB \fR\- export type name. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
env
.SH FILES
.PP
REnv.dll
.PP
.SH COPYRIGHT
GPL3
